// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: procmesh/v1/access.proto

package procmeshv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/qleelulu/procmesh/proto/procmesh/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "procmesh.v1.UserService"
	// RoleServiceName is the fully-qualified name of the RoleService service.
	RoleServiceName = "procmesh.v1.RoleService"
	// GroupServiceName is the fully-qualified name of the GroupService service.
	GroupServiceName = "procmesh.v1.GroupService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceListUsersProcedure is the fully-qualified name of the UserService's ListUsers RPC.
	UserServiceListUsersProcedure = "/procmesh.v1.UserService/ListUsers"
	// UserServiceCreateUserProcedure is the fully-qualified name of the UserService's CreateUser RPC.
	UserServiceCreateUserProcedure = "/procmesh.v1.UserService/CreateUser"
	// UserServiceDisableUserProcedure is the fully-qualified name of the UserService's DisableUser RPC.
	UserServiceDisableUserProcedure = "/procmesh.v1.UserService/DisableUser"
	// UserServiceEnableUserProcedure is the fully-qualified name of the UserService's EnableUser RPC.
	UserServiceEnableUserProcedure = "/procmesh.v1.UserService/EnableUser"
	// RoleServiceListRolesProcedure is the fully-qualified name of the RoleService's ListRoles RPC.
	RoleServiceListRolesProcedure = "/procmesh.v1.RoleService/ListRoles"
	// RoleServiceCreateRoleProcedure is the fully-qualified name of the RoleService's CreateRole RPC.
	RoleServiceCreateRoleProcedure = "/procmesh.v1.RoleService/CreateRole"
	// RoleServiceUpdateRoleProcedure is the fully-qualified name of the RoleService's UpdateRole RPC.
	RoleServiceUpdateRoleProcedure = "/procmesh.v1.RoleService/UpdateRole"
	// RoleServiceDeleteRoleProcedure is the fully-qualified name of the RoleService's DeleteRole RPC.
	RoleServiceDeleteRoleProcedure = "/procmesh.v1.RoleService/DeleteRole"
	// RoleServiceGrantRoleProcedure is the fully-qualified name of the RoleService's GrantRole RPC.
	RoleServiceGrantRoleProcedure = "/procmesh.v1.RoleService/GrantRole"
	// RoleServiceRevokeRoleProcedure is the fully-qualified name of the RoleService's RevokeRole RPC.
	RoleServiceRevokeRoleProcedure = "/procmesh.v1.RoleService/RevokeRole"
	// GroupServiceListAgentGroupsProcedure is the fully-qualified name of the GroupService's
	// ListAgentGroups RPC.
	GroupServiceListAgentGroupsProcedure = "/procmesh.v1.GroupService/ListAgentGroups"
	// GroupServiceCreateAgentGroupProcedure is the fully-qualified name of the GroupService's
	// CreateAgentGroup RPC.
	GroupServiceCreateAgentGroupProcedure = "/procmesh.v1.GroupService/CreateAgentGroup"
	// GroupServiceDeleteAgentGroupProcedure is the fully-qualified name of the GroupService's
	// DeleteAgentGroup RPC.
	GroupServiceDeleteAgentGroupProcedure = "/procmesh.v1.GroupService/DeleteAgentGroup"
	// GroupServiceAddAgentGroupMemberProcedure is the fully-qualified name of the GroupService's
	// AddAgentGroupMember RPC.
	GroupServiceAddAgentGroupMemberProcedure = "/procmesh.v1.GroupService/AddAgentGroupMember"
	// GroupServiceRemoveAgentGroupMemberProcedure is the fully-qualified name of the GroupService's
	// RemoveAgentGroupMember RPC.
	GroupServiceRemoveAgentGroupMemberProcedure = "/procmesh.v1.GroupService/RemoveAgentGroupMember"
)

// UserServiceClient is a client for the procmesh.v1.UserService service.
type UserServiceClient interface {
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	DisableUser(context.Context, *connect.Request[v1.DisableUserRequest]) (*connect.Response[v1.DisableUserResponse], error)
	EnableUser(context.Context, *connect.Request[v1.EnableUserRequest]) (*connect.Response[v1.EnableUserResponse], error)
}

// NewUserServiceClient constructs a client for the procmesh.v1.UserService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := v1.File_procmesh_v1_access_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		listUsers: connect.NewClient[v1.ListUsersRequest, v1.ListUsersResponse](
			httpClient,
			baseURL+UserServiceListUsersProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		createUser: connect.NewClient[v1.CreateUserRequest, v1.CreateUserResponse](
			httpClient,
			baseURL+UserServiceCreateUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		disableUser: connect.NewClient[v1.DisableUserRequest, v1.DisableUserResponse](
			httpClient,
			baseURL+UserServiceDisableUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("DisableUser")),
			connect.WithClientOptions(opts...),
		),
		enableUser: connect.NewClient[v1.EnableUserRequest, v1.EnableUserResponse](
			httpClient,
			baseURL+UserServiceEnableUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("EnableUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	listUsers   *connect.Client[v1.ListUsersRequest, v1.ListUsersResponse]
	createUser  *connect.Client[v1.CreateUserRequest, v1.CreateUserResponse]
	disableUser *connect.Client[v1.DisableUserRequest, v1.DisableUserResponse]
	enableUser  *connect.Client[v1.EnableUserRequest, v1.EnableUserResponse]
}

// ListUsers calls procmesh.v1.UserService.ListUsers.
func (c *userServiceClient) ListUsers(ctx context.Context, req *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// CreateUser calls procmesh.v1.UserService.CreateUser.
func (c *userServiceClient) CreateUser(ctx context.Context, req *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// DisableUser calls procmesh.v1.UserService.DisableUser.
func (c *userServiceClient) DisableUser(ctx context.Context, req *connect.Request[v1.DisableUserRequest]) (*connect.Response[v1.DisableUserResponse], error) {
	return c.disableUser.CallUnary(ctx, req)
}

// EnableUser calls procmesh.v1.UserService.EnableUser.
func (c *userServiceClient) EnableUser(ctx context.Context, req *connect.Request[v1.EnableUserRequest]) (*connect.Response[v1.EnableUserResponse], error) {
	return c.enableUser.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the procmesh.v1.UserService service.
type UserServiceHandler interface {
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	DisableUser(context.Context, *connect.Request[v1.DisableUserRequest]) (*connect.Response[v1.DisableUserResponse], error)
	EnableUser(context.Context, *connect.Request[v1.EnableUserRequest]) (*connect.Response[v1.EnableUserResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := v1.File_procmesh_v1_access_proto.Services().ByName("UserService").Methods()
	userServiceListUsersHandler := connect.NewUnaryHandler(
		UserServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(userServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceCreateUserHandler := connect.NewUnaryHandler(
		UserServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(userServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceDisableUserHandler := connect.NewUnaryHandler(
		UserServiceDisableUserProcedure,
		svc.DisableUser,
		connect.WithSchema(userServiceMethods.ByName("DisableUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceEnableUserHandler := connect.NewUnaryHandler(
		UserServiceEnableUserProcedure,
		svc.EnableUser,
		connect.WithSchema(userServiceMethods.ByName("EnableUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/procmesh.v1.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceListUsersProcedure:
			userServiceListUsersHandler.ServeHTTP(w, r)
		case UserServiceCreateUserProcedure:
			userServiceCreateUserHandler.ServeHTTP(w, r)
		case UserServiceDisableUserProcedure:
			userServiceDisableUserHandler.ServeHTTP(w, r)
		case UserServiceEnableUserProcedure:
			userServiceEnableUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.UserService.ListUsers is not implemented"))
}

func (UnimplementedUserServiceHandler) CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.UserService.CreateUser is not implemented"))
}

func (UnimplementedUserServiceHandler) DisableUser(context.Context, *connect.Request[v1.DisableUserRequest]) (*connect.Response[v1.DisableUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.UserService.DisableUser is not implemented"))
}

func (UnimplementedUserServiceHandler) EnableUser(context.Context, *connect.Request[v1.EnableUserRequest]) (*connect.Response[v1.EnableUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.UserService.EnableUser is not implemented"))
}

// RoleServiceClient is a client for the procmesh.v1.RoleService service.
type RoleServiceClient interface {
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
	CreateRole(context.Context, *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error)
	UpdateRole(context.Context, *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error)
	DeleteRole(context.Context, *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error)
	GrantRole(context.Context, *connect.Request[v1.GrantRoleRequest]) (*connect.Response[v1.GrantRoleResponse], error)
	RevokeRole(context.Context, *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error)
}

// NewRoleServiceClient constructs a client for the procmesh.v1.RoleService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRoleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RoleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	roleServiceMethods := v1.File_procmesh_v1_access_proto.Services().ByName("RoleService").Methods()
	return &roleServiceClient{
		listRoles: connect.NewClient[v1.ListRolesRequest, v1.ListRolesResponse](
			httpClient,
			baseURL+RoleServiceListRolesProcedure,
			connect.WithSchema(roleServiceMethods.ByName("ListRoles")),
			connect.WithClientOptions(opts...),
		),
		createRole: connect.NewClient[v1.CreateRoleRequest, v1.CreateRoleResponse](
			httpClient,
			baseURL+RoleServiceCreateRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("CreateRole")),
			connect.WithClientOptions(opts...),
		),
		updateRole: connect.NewClient[v1.UpdateRoleRequest, v1.UpdateRoleResponse](
			httpClient,
			baseURL+RoleServiceUpdateRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("UpdateRole")),
			connect.WithClientOptions(opts...),
		),
		deleteRole: connect.NewClient[v1.DeleteRoleRequest, v1.DeleteRoleResponse](
			httpClient,
			baseURL+RoleServiceDeleteRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("DeleteRole")),
			connect.WithClientOptions(opts...),
		),
		grantRole: connect.NewClient[v1.GrantRoleRequest, v1.GrantRoleResponse](
			httpClient,
			baseURL+RoleServiceGrantRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("GrantRole")),
			connect.WithClientOptions(opts...),
		),
		revokeRole: connect.NewClient[v1.RevokeRoleRequest, v1.RevokeRoleResponse](
			httpClient,
			baseURL+RoleServiceRevokeRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("RevokeRole")),
			connect.WithClientOptions(opts...),
		),
	}
}

// roleServiceClient implements RoleServiceClient.
type roleServiceClient struct {
	listRoles  *connect.Client[v1.ListRolesRequest, v1.ListRolesResponse]
	createRole *connect.Client[v1.CreateRoleRequest, v1.CreateRoleResponse]
	updateRole *connect.Client[v1.UpdateRoleRequest, v1.UpdateRoleResponse]
	deleteRole *connect.Client[v1.DeleteRoleRequest, v1.DeleteRoleResponse]
	grantRole  *connect.Client[v1.GrantRoleRequest, v1.GrantRoleResponse]
	revokeRole *connect.Client[v1.RevokeRoleRequest, v1.RevokeRoleResponse]
}

// ListRoles calls procmesh.v1.RoleService.ListRoles.
func (c *roleServiceClient) ListRoles(ctx context.Context, req *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return c.listRoles.CallUnary(ctx, req)
}

// CreateRole calls procmesh.v1.RoleService.CreateRole.
func (c *roleServiceClient) CreateRole(ctx context.Context, req *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error) {
	return c.createRole.CallUnary(ctx, req)
}

// UpdateRole calls procmesh.v1.RoleService.UpdateRole.
func (c *roleServiceClient) UpdateRole(ctx context.Context, req *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error) {
	return c.updateRole.CallUnary(ctx, req)
}

// DeleteRole calls procmesh.v1.RoleService.DeleteRole.
func (c *roleServiceClient) DeleteRole(ctx context.Context, req *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error) {
	return c.deleteRole.CallUnary(ctx, req)
}

// GrantRole calls procmesh.v1.RoleService.GrantRole.
func (c *roleServiceClient) GrantRole(ctx context.Context, req *connect.Request[v1.GrantRoleRequest]) (*connect.Response[v1.GrantRoleResponse], error) {
	return c.grantRole.CallUnary(ctx, req)
}

// RevokeRole calls procmesh.v1.RoleService.RevokeRole.
func (c *roleServiceClient) RevokeRole(ctx context.Context, req *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error) {
	return c.revokeRole.CallUnary(ctx, req)
}

// RoleServiceHandler is an implementation of the procmesh.v1.RoleService service.
type RoleServiceHandler interface {
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
	CreateRole(context.Context, *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error)
	UpdateRole(context.Context, *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error)
	DeleteRole(context.Context, *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error)
	GrantRole(context.Context, *connect.Request[v1.GrantRoleRequest]) (*connect.Response[v1.GrantRoleResponse], error)
	RevokeRole(context.Context, *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error)
}

// NewRoleServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRoleServiceHandler(svc RoleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	roleServiceMethods := v1.File_procmesh_v1_access_proto.Services().ByName("RoleService").Methods()
	roleServiceListRolesHandler := connect.NewUnaryHandler(
		RoleServiceListRolesProcedure,
		svc.ListRoles,
		connect.WithSchema(roleServiceMethods.ByName("ListRoles")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceCreateRoleHandler := connect.NewUnaryHandler(
		RoleServiceCreateRoleProcedure,
		svc.CreateRole,
		connect.WithSchema(roleServiceMethods.ByName("CreateRole")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceUpdateRoleHandler := connect.NewUnaryHandler(
		RoleServiceUpdateRoleProcedure,
		svc.UpdateRole,
		connect.WithSchema(roleServiceMethods.ByName("UpdateRole")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceDeleteRoleHandler := connect.NewUnaryHandler(
		RoleServiceDeleteRoleProcedure,
		svc.DeleteRole,
		connect.WithSchema(roleServiceMethods.ByName("DeleteRole")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceGrantRoleHandler := connect.NewUnaryHandler(
		RoleServiceGrantRoleProcedure,
		svc.GrantRole,
		connect.WithSchema(roleServiceMethods.ByName("GrantRole")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceRevokeRoleHandler := connect.NewUnaryHandler(
		RoleServiceRevokeRoleProcedure,
		svc.RevokeRole,
		connect.WithSchema(roleServiceMethods.ByName("RevokeRole")),
		connect.WithHandlerOptions(opts...),
	)
	return "/procmesh.v1.RoleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RoleServiceListRolesProcedure:
			roleServiceListRolesHandler.ServeHTTP(w, r)
		case RoleServiceCreateRoleProcedure:
			roleServiceCreateRoleHandler.ServeHTTP(w, r)
		case RoleServiceUpdateRoleProcedure:
			roleServiceUpdateRoleHandler.ServeHTTP(w, r)
		case RoleServiceDeleteRoleProcedure:
			roleServiceDeleteRoleHandler.ServeHTTP(w, r)
		case RoleServiceGrantRoleProcedure:
			roleServiceGrantRoleHandler.ServeHTTP(w, r)
		case RoleServiceRevokeRoleProcedure:
			roleServiceRevokeRoleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRoleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRoleServiceHandler struct{}

func (UnimplementedRoleServiceHandler) ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.RoleService.ListRoles is not implemented"))
}

func (UnimplementedRoleServiceHandler) CreateRole(context.Context, *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.RoleService.CreateRole is not implemented"))
}

func (UnimplementedRoleServiceHandler) UpdateRole(context.Context, *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.RoleService.UpdateRole is not implemented"))
}

func (UnimplementedRoleServiceHandler) DeleteRole(context.Context, *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.RoleService.DeleteRole is not implemented"))
}

func (UnimplementedRoleServiceHandler) GrantRole(context.Context, *connect.Request[v1.GrantRoleRequest]) (*connect.Response[v1.GrantRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.RoleService.GrantRole is not implemented"))
}

func (UnimplementedRoleServiceHandler) RevokeRole(context.Context, *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.RoleService.RevokeRole is not implemented"))
}

// GroupServiceClient is a client for the procmesh.v1.GroupService service.
type GroupServiceClient interface {
	ListAgentGroups(context.Context, *connect.Request[v1.ListAgentGroupsRequest]) (*connect.Response[v1.ListAgentGroupsResponse], error)
	CreateAgentGroup(context.Context, *connect.Request[v1.CreateAgentGroupRequest]) (*connect.Response[v1.CreateAgentGroupResponse], error)
	DeleteAgentGroup(context.Context, *connect.Request[v1.DeleteAgentGroupRequest]) (*connect.Response[v1.DeleteAgentGroupResponse], error)
	AddAgentGroupMember(context.Context, *connect.Request[v1.AgentGroupMemberRequest]) (*connect.Response[v1.AgentGroupMemberResponse], error)
	RemoveAgentGroupMember(context.Context, *connect.Request[v1.AgentGroupMemberRequest]) (*connect.Response[v1.AgentGroupMemberResponse], error)
}

// NewGroupServiceClient constructs a client for the procmesh.v1.GroupService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGroupServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GroupServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	groupServiceMethods := v1.File_procmesh_v1_access_proto.Services().ByName("GroupService").Methods()
	return &groupServiceClient{
		listAgentGroups: connect.NewClient[v1.ListAgentGroupsRequest, v1.ListAgentGroupsResponse](
			httpClient,
			baseURL+GroupServiceListAgentGroupsProcedure,
			connect.WithSchema(groupServiceMethods.ByName("ListAgentGroups")),
			connect.WithClientOptions(opts...),
		),
		createAgentGroup: connect.NewClient[v1.CreateAgentGroupRequest, v1.CreateAgentGroupResponse](
			httpClient,
			baseURL+GroupServiceCreateAgentGroupProcedure,
			connect.WithSchema(groupServiceMethods.ByName("CreateAgentGroup")),
			connect.WithClientOptions(opts...),
		),
		deleteAgentGroup: connect.NewClient[v1.DeleteAgentGroupRequest, v1.DeleteAgentGroupResponse](
			httpClient,
			baseURL+GroupServiceDeleteAgentGroupProcedure,
			connect.WithSchema(groupServiceMethods.ByName("DeleteAgentGroup")),
			connect.WithClientOptions(opts...),
		),
		addAgentGroupMember: connect.NewClient[v1.AgentGroupMemberRequest, v1.AgentGroupMemberResponse](
			httpClient,
			baseURL+GroupServiceAddAgentGroupMemberProcedure,
			connect.WithSchema(groupServiceMethods.ByName("AddAgentGroupMember")),
			connect.WithClientOptions(opts...),
		),
		removeAgentGroupMember: connect.NewClient[v1.AgentGroupMemberRequest, v1.AgentGroupMemberResponse](
			httpClient,
			baseURL+GroupServiceRemoveAgentGroupMemberProcedure,
			connect.WithSchema(groupServiceMethods.ByName("RemoveAgentGroupMember")),
			connect.WithClientOptions(opts...),
		),
	}
}

// groupServiceClient implements GroupServiceClient.
type groupServiceClient struct {
	listAgentGroups        *connect.Client[v1.ListAgentGroupsRequest, v1.ListAgentGroupsResponse]
	createAgentGroup       *connect.Client[v1.CreateAgentGroupRequest, v1.CreateAgentGroupResponse]
	deleteAgentGroup       *connect.Client[v1.DeleteAgentGroupRequest, v1.DeleteAgentGroupResponse]
	addAgentGroupMember    *connect.Client[v1.AgentGroupMemberRequest, v1.AgentGroupMemberResponse]
	removeAgentGroupMember *connect.Client[v1.AgentGroupMemberRequest, v1.AgentGroupMemberResponse]
}

// ListAgentGroups calls procmesh.v1.GroupService.ListAgentGroups.
func (c *groupServiceClient) ListAgentGroups(ctx context.Context, req *connect.Request[v1.ListAgentGroupsRequest]) (*connect.Response[v1.ListAgentGroupsResponse], error) {
	return c.listAgentGroups.CallUnary(ctx, req)
}

// CreateAgentGroup calls procmesh.v1.GroupService.CreateAgentGroup.
func (c *groupServiceClient) CreateAgentGroup(ctx context.Context, req *connect.Request[v1.CreateAgentGroupRequest]) (*connect.Response[v1.CreateAgentGroupResponse], error) {
	return c.createAgentGroup.CallUnary(ctx, req)
}

// DeleteAgentGroup calls procmesh.v1.GroupService.DeleteAgentGroup.
func (c *groupServiceClient) DeleteAgentGroup(ctx context.Context, req *connect.Request[v1.DeleteAgentGroupRequest]) (*connect.Response[v1.DeleteAgentGroupResponse], error) {
	return c.deleteAgentGroup.CallUnary(ctx, req)
}

// AddAgentGroupMember calls procmesh.v1.GroupService.AddAgentGroupMember.
func (c *groupServiceClient) AddAgentGroupMember(ctx context.Context, req *connect.Request[v1.AgentGroupMemberRequest]) (*connect.Response[v1.AgentGroupMemberResponse], error) {
	return c.addAgentGroupMember.CallUnary(ctx, req)
}

// RemoveAgentGroupMember calls procmesh.v1.GroupService.RemoveAgentGroupMember.
func (c *groupServiceClient) RemoveAgentGroupMember(ctx context.Context, req *connect.Request[v1.AgentGroupMemberRequest]) (*connect.Response[v1.AgentGroupMemberResponse], error) {
	return c.removeAgentGroupMember.CallUnary(ctx, req)
}

// GroupServiceHandler is an implementation of the procmesh.v1.GroupService service.
type GroupServiceHandler interface {
	ListAgentGroups(context.Context, *connect.Request[v1.ListAgentGroupsRequest]) (*connect.Response[v1.ListAgentGroupsResponse], error)
	CreateAgentGroup(context.Context, *connect.Request[v1.CreateAgentGroupRequest]) (*connect.Response[v1.CreateAgentGroupResponse], error)
	DeleteAgentGroup(context.Context, *connect.Request[v1.DeleteAgentGroupRequest]) (*connect.Response[v1.DeleteAgentGroupResponse], error)
	AddAgentGroupMember(context.Context, *connect.Request[v1.AgentGroupMemberRequest]) (*connect.Response[v1.AgentGroupMemberResponse], error)
	RemoveAgentGroupMember(context.Context, *connect.Request[v1.AgentGroupMemberRequest]) (*connect.Response[v1.AgentGroupMemberResponse], error)
}

// NewGroupServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGroupServiceHandler(svc GroupServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	groupServiceMethods := v1.File_procmesh_v1_access_proto.Services().ByName("GroupService").Methods()
	groupServiceListAgentGroupsHandler := connect.NewUnaryHandler(
		GroupServiceListAgentGroupsProcedure,
		svc.ListAgentGroups,
		connect.WithSchema(groupServiceMethods.ByName("ListAgentGroups")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceCreateAgentGroupHandler := connect.NewUnaryHandler(
		GroupServiceCreateAgentGroupProcedure,
		svc.CreateAgentGroup,
		connect.WithSchema(groupServiceMethods.ByName("CreateAgentGroup")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceDeleteAgentGroupHandler := connect.NewUnaryHandler(
		GroupServiceDeleteAgentGroupProcedure,
		svc.DeleteAgentGroup,
		connect.WithSchema(groupServiceMethods.ByName("DeleteAgentGroup")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceAddAgentGroupMemberHandler := connect.NewUnaryHandler(
		GroupServiceAddAgentGroupMemberProcedure,
		svc.AddAgentGroupMember,
		connect.WithSchema(groupServiceMethods.ByName("AddAgentGroupMember")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceRemoveAgentGroupMemberHandler := connect.NewUnaryHandler(
		GroupServiceRemoveAgentGroupMemberProcedure,
		svc.RemoveAgentGroupMember,
		connect.WithSchema(groupServiceMethods.ByName("RemoveAgentGroupMember")),
		connect.WithHandlerOptions(opts...),
	)
	return "/procmesh.v1.GroupService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GroupServiceListAgentGroupsProcedure:
			groupServiceListAgentGroupsHandler.ServeHTTP(w, r)
		case GroupServiceCreateAgentGroupProcedure:
			groupServiceCreateAgentGroupHandler.ServeHTTP(w, r)
		case GroupServiceDeleteAgentGroupProcedure:
			groupServiceDeleteAgentGroupHandler.ServeHTTP(w, r)
		case GroupServiceAddAgentGroupMemberProcedure:
			groupServiceAddAgentGroupMemberHandler.ServeHTTP(w, r)
		case GroupServiceRemoveAgentGroupMemberProcedure:
			groupServiceRemoveAgentGroupMemberHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGroupServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGroupServiceHandler struct{}

func (UnimplementedGroupServiceHandler) ListAgentGroups(context.Context, *connect.Request[v1.ListAgentGroupsRequest]) (*connect.Response[v1.ListAgentGroupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.GroupService.ListAgentGroups is not implemented"))
}

func (UnimplementedGroupServiceHandler) CreateAgentGroup(context.Context, *connect.Request[v1.CreateAgentGroupRequest]) (*connect.Response[v1.CreateAgentGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.GroupService.CreateAgentGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) DeleteAgentGroup(context.Context, *connect.Request[v1.DeleteAgentGroupRequest]) (*connect.Response[v1.DeleteAgentGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.GroupService.DeleteAgentGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) AddAgentGroupMember(context.Context, *connect.Request[v1.AgentGroupMemberRequest]) (*connect.Response[v1.AgentGroupMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.GroupService.AddAgentGroupMember is not implemented"))
}

func (UnimplementedGroupServiceHandler) RemoveAgentGroupMember(context.Context, *connect.Request[v1.AgentGroupMemberRequest]) (*connect.Response[v1.AgentGroupMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.GroupService.RemoveAgentGroupMember is not implemented"))
}
