// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: procmesh/v1/workload_summary.proto

package procmeshv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/qleelulu/procmesh/proto/procmesh/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkloadSummaryServiceName is the fully-qualified name of the WorkloadSummaryService service.
	WorkloadSummaryServiceName = "procmesh.v1.WorkloadSummaryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkloadSummaryServiceFetchWorkloadSnapshotProcedure is the fully-qualified name of the
	// WorkloadSummaryService's FetchWorkloadSnapshot RPC.
	WorkloadSummaryServiceFetchWorkloadSnapshotProcedure = "/procmesh.v1.WorkloadSummaryService/FetchWorkloadSnapshot"
)

// WorkloadSummaryServiceClient is a client for the procmesh.v1.WorkloadSummaryService service.
type WorkloadSummaryServiceClient interface {
	FetchWorkloadSnapshot(context.Context, *connect.Request[v1.FetchWorkloadSnapshotRequest]) (*connect.ServerStreamForClient[v1.WorkloadSnapshotChunk], error)
}

// NewWorkloadSummaryServiceClient constructs a client for the procmesh.v1.WorkloadSummaryService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkloadSummaryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkloadSummaryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workloadSummaryServiceMethods := v1.File_procmesh_v1_workload_summary_proto.Services().ByName("WorkloadSummaryService").Methods()
	return &workloadSummaryServiceClient{
		fetchWorkloadSnapshot: connect.NewClient[v1.FetchWorkloadSnapshotRequest, v1.WorkloadSnapshotChunk](
			httpClient,
			baseURL+WorkloadSummaryServiceFetchWorkloadSnapshotProcedure,
			connect.WithSchema(workloadSummaryServiceMethods.ByName("FetchWorkloadSnapshot")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workloadSummaryServiceClient implements WorkloadSummaryServiceClient.
type workloadSummaryServiceClient struct {
	fetchWorkloadSnapshot *connect.Client[v1.FetchWorkloadSnapshotRequest, v1.WorkloadSnapshotChunk]
}

// FetchWorkloadSnapshot calls procmesh.v1.WorkloadSummaryService.FetchWorkloadSnapshot.
func (c *workloadSummaryServiceClient) FetchWorkloadSnapshot(ctx context.Context, req *connect.Request[v1.FetchWorkloadSnapshotRequest]) (*connect.ServerStreamForClient[v1.WorkloadSnapshotChunk], error) {
	return c.fetchWorkloadSnapshot.CallServerStream(ctx, req)
}

// WorkloadSummaryServiceHandler is an implementation of the procmesh.v1.WorkloadSummaryService
// service.
type WorkloadSummaryServiceHandler interface {
	FetchWorkloadSnapshot(context.Context, *connect.Request[v1.FetchWorkloadSnapshotRequest], *connect.ServerStream[v1.WorkloadSnapshotChunk]) error
}

// NewWorkloadSummaryServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkloadSummaryServiceHandler(svc WorkloadSummaryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workloadSummaryServiceMethods := v1.File_procmesh_v1_workload_summary_proto.Services().ByName("WorkloadSummaryService").Methods()
	workloadSummaryServiceFetchWorkloadSnapshotHandler := connect.NewServerStreamHandler(
		WorkloadSummaryServiceFetchWorkloadSnapshotProcedure,
		svc.FetchWorkloadSnapshot,
		connect.WithSchema(workloadSummaryServiceMethods.ByName("FetchWorkloadSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	return "/procmesh.v1.WorkloadSummaryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkloadSummaryServiceFetchWorkloadSnapshotProcedure:
			workloadSummaryServiceFetchWorkloadSnapshotHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkloadSummaryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkloadSummaryServiceHandler struct{}

func (UnimplementedWorkloadSummaryServiceHandler) FetchWorkloadSnapshot(context.Context, *connect.Request[v1.FetchWorkloadSnapshotRequest], *connect.ServerStream[v1.WorkloadSnapshotChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("procmesh.v1.WorkloadSummaryService.FetchWorkloadSnapshot is not implemented"))
}
