package auth

const (
	PermClusterRead         = "cluster.read"
	PermClusterManage       = "cluster.manage"
	PermNodeRead            = "node.read"
	PermNodeManage          = "node.manage"
	PermNodeRemove          = "node.remove"
	PermProcessRead         = "process.read"
	PermProcessCreate       = "process.create"
	PermProcessUpdate       = "process.update"
	PermProcessDelete       = "process.delete"
	PermProcessStart        = "process.start"
	PermProcessStop         = "process.stop"
	PermProcessRestart      = "process.restart"
	PermProcessConfigRead   = "process.config.read"
	PermProcessConfigUpdate = "process.config.update"
	PermProcessLogsRead     = "process.logs.read"
	PermProcessLogsDownload = "process.logs.download"
	PermUserRead            = "user.read"
	PermUserCreate          = "user.create"
	PermUserUpdate          = "user.update"
	PermUserDelete          = "user.delete"
	PermRoleRead            = "role.read"
	PermRoleManage          = "role.manage"
	PermAuditRead           = "audit.read"
	PermCommandExecute      = "command.execute"
	PermCommandExecuteBatch = "command.execute.batch"
	CookieName              = "procmesh_session"
	HeaderCSRF              = "X-CSRF-Token"
)
