// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: procmesh/v1/alert.proto

package procmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Alert struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AlertId        string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Fingerprint    string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Severity       string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	NodeId         string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ProcessId      string                 `protobuf:"bytes,6,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	PayloadJson    string                 `protobuf:"bytes,7,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	State          string                 `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"` // FIRING | RESOLVED
	FirstUnixMs    int64                  `protobuf:"varint,9,opt,name=first_unix_ms,json=firstUnixMs,proto3" json:"first_unix_ms,omitempty"`
	LastUnixMs     int64                  `protobuf:"varint,10,opt,name=last_unix_ms,json=lastUnixMs,proto3" json:"last_unix_ms,omitempty"`
	NotifiedUnixMs int64                  `protobuf:"varint,11,opt,name=notified_unix_ms,json=notifiedUnixMs,proto3" json:"notified_unix_ms,omitempty"`
	ResolvedUnixMs int64                  `protobuf:"varint,12,opt,name=resolved_unix_ms,json=resolvedUnixMs,proto3" json:"resolved_unix_ms,omitempty"`
	LastError      string                 `protobuf:"bytes,13,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{0}
}

func (x *Alert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *Alert) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Alert) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Alert) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Alert) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *Alert) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Alert) GetFirstUnixMs() int64 {
	if x != nil {
		return x.FirstUnixMs
	}
	return 0
}

func (x *Alert) GetLastUnixMs() int64 {
	if x != nil {
		return x.LastUnixMs
	}
	return 0
}

func (x *Alert) GetNotifiedUnixMs() int64 {
	if x != nil {
		return x.NotifiedUnixMs
	}
	return 0
}

func (x *Alert) GetResolvedUnixMs() int64 {
	if x != nil {
		return x.ResolvedUnixMs
	}
	return 0
}

func (x *Alert) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type AlertEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Alert             *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	SourceNode        string                 `protobuf:"bytes,2,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	Freshness         string                 `protobuf:"bytes,3,opt,name=freshness,proto3" json:"freshness,omitempty"` // LIVE | STALE | UNKNOWN
	LastUpdatedUnixMs int64                  `protobuf:"varint,4,opt,name=last_updated_unix_ms,json=lastUpdatedUnixMs,proto3" json:"last_updated_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AlertEntry) Reset() {
	*x = AlertEntry{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertEntry) ProtoMessage() {}

func (x *AlertEntry) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertEntry.ProtoReflect.Descriptor instead.
func (*AlertEntry) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{1}
}

func (x *AlertEntry) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

func (x *AlertEntry) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *AlertEntry) GetFreshness() string {
	if x != nil {
		return x.Freshness
	}
	return ""
}

func (x *AlertEntry) GetLastUpdatedUnixMs() int64 {
	if x != nil {
		return x.LastUpdatedUnixMs
	}
	return 0
}

type ListAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`                            // 0 = 50；封顶 200
	TargetNode    string                 `protobuf:"bytes,2,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"` // 空 = 聚合
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`                             // 空 = 全部；FIRING | RESOLVED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsRequest) Reset() {
	*x = ListAlertsRequest{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsRequest) ProtoMessage() {}

func (x *ListAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListAlertsRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{2}
}

func (x *ListAlertsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAlertsRequest) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

func (x *ListAlertsRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ListAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AlertEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsResponse) Reset() {
	*x = ListAlertsResponse{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsResponse) ProtoMessage() {}

func (x *ListAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertsResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{3}
}

func (x *ListAlertsResponse) GetEntries() []*AlertEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRequest) Reset() {
	*x = GetAlertRequest{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRequest) ProtoMessage() {}

func (x *GetAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{4}
}

func (x *GetAlertRequest) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

type GetAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *AlertEntry            `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertResponse) Reset() {
	*x = GetAlertResponse{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertResponse) ProtoMessage() {}

func (x *GetAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertResponse.ProtoReflect.Descriptor instead.
func (*GetAlertResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{5}
}

func (x *GetAlertResponse) GetEntry() *AlertEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type AlertChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,5,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // 已脱敏
	CreatedUnix   int64                  `protobuf:"varint,6,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	UpdatedUnix   int64                  `protobuf:"varint,7,opt,name=updated_unix,json=updatedUnix,proto3" json:"updated_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertChannel) Reset() {
	*x = AlertChannel{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertChannel) ProtoMessage() {}

func (x *AlertChannel) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertChannel.ProtoReflect.Descriptor instead.
func (*AlertChannel) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{6}
}

func (x *AlertChannel) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *AlertChannel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AlertChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertChannel) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AlertChannel) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *AlertChannel) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

func (x *AlertChannel) GetUpdatedUnix() int64 {
	if x != nil {
		return x.UpdatedUnix
	}
	return 0
}

type ListAlertChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertChannelsRequest) Reset() {
	*x = ListAlertChannelsRequest{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertChannelsRequest) ProtoMessage() {}

func (x *ListAlertChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListAlertChannelsRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{7}
}

type ListAlertChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*AlertChannel        `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertChannelsResponse) Reset() {
	*x = ListAlertChannelsResponse{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertChannelsResponse) ProtoMessage() {}

func (x *ListAlertChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertChannelsResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{8}
}

func (x *ListAlertChannelsResponse) GetChannels() []*AlertChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type PutAlertChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MutationMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // 空 = 创建
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,6,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAlertChannelRequest) Reset() {
	*x = PutAlertChannelRequest{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAlertChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAlertChannelRequest) ProtoMessage() {}

func (x *PutAlertChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAlertChannelRequest.ProtoReflect.Descriptor instead.
func (*PutAlertChannelRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{9}
}

func (x *PutAlertChannelRequest) GetMeta() *MutationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PutAlertChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *PutAlertChannelRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PutAlertChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutAlertChannelRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PutAlertChannelRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type PutAlertChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *AlertChannel          `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAlertChannelResponse) Reset() {
	*x = PutAlertChannelResponse{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAlertChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAlertChannelResponse) ProtoMessage() {}

func (x *PutAlertChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAlertChannelResponse.ProtoReflect.Descriptor instead.
func (*PutAlertChannelResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{10}
}

func (x *PutAlertChannelResponse) GetChannel() *AlertChannel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type DeleteAlertChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MutationMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertChannelRequest) Reset() {
	*x = DeleteAlertChannelRequest{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertChannelRequest) ProtoMessage() {}

func (x *DeleteAlertChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertChannelRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlertChannelRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAlertChannelRequest) GetMeta() *MutationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DeleteAlertChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type DeleteAlertChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertChannelResponse) Reset() {
	*x = DeleteAlertChannelResponse{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertChannelResponse) ProtoMessage() {}

func (x *DeleteAlertChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertChannelResponse.ProtoReflect.Descriptor instead.
func (*DeleteAlertChannelResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{12}
}

type TestAlertChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MutationMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAlertChannelRequest) Reset() {
	*x = TestAlertChannelRequest{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAlertChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAlertChannelRequest) ProtoMessage() {}

func (x *TestAlertChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAlertChannelRequest.ProtoReflect.Descriptor instead.
func (*TestAlertChannelRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{13}
}

func (x *TestAlertChannelRequest) GetMeta() *MutationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TestAlertChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type TestAlertChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAlertChannelResponse) Reset() {
	*x = TestAlertChannelResponse{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAlertChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAlertChannelResponse) ProtoMessage() {}

func (x *TestAlertChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAlertChannelResponse.ProtoReflect.Descriptor instead.
func (*TestAlertChannelResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{14}
}

type AlertPolicy struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DedupWindowSec      int64                  `protobuf:"varint,1,opt,name=dedup_window_sec,json=dedupWindowSec,proto3" json:"dedup_window_sec,omitempty"`
	NotifyOnResolve     bool                   `protobuf:"varint,2,opt,name=notify_on_resolve,json=notifyOnResolve,proto3" json:"notify_on_resolve,omitempty"`
	CpuHighPercent      int32                  `protobuf:"varint,3,opt,name=cpu_high_percent,json=cpuHighPercent,proto3" json:"cpu_high_percent,omitempty"`
	MemoryHighPercent   int32                  `protobuf:"varint,4,opt,name=memory_high_percent,json=memoryHighPercent,proto3" json:"memory_high_percent,omitempty"`
	DiskHighPercent     int32                  `protobuf:"varint,5,opt,name=disk_high_percent,json=diskHighPercent,proto3" json:"disk_high_percent,omitempty"`
	HighConsecutiveMins int32                  `protobuf:"varint,6,opt,name=high_consecutive_mins,json=highConsecutiveMins,proto3" json:"high_consecutive_mins,omitempty"`
	SuspectTooLongSec   int64                  `protobuf:"varint,7,opt,name=suspect_too_long_sec,json=suspectTooLongSec,proto3" json:"suspect_too_long_sec,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AlertPolicy) Reset() {
	*x = AlertPolicy{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertPolicy) ProtoMessage() {}

func (x *AlertPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertPolicy.ProtoReflect.Descriptor instead.
func (*AlertPolicy) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{15}
}

func (x *AlertPolicy) GetDedupWindowSec() int64 {
	if x != nil {
		return x.DedupWindowSec
	}
	return 0
}

func (x *AlertPolicy) GetNotifyOnResolve() bool {
	if x != nil {
		return x.NotifyOnResolve
	}
	return false
}

func (x *AlertPolicy) GetCpuHighPercent() int32 {
	if x != nil {
		return x.CpuHighPercent
	}
	return 0
}

func (x *AlertPolicy) GetMemoryHighPercent() int32 {
	if x != nil {
		return x.MemoryHighPercent
	}
	return 0
}

func (x *AlertPolicy) GetDiskHighPercent() int32 {
	if x != nil {
		return x.DiskHighPercent
	}
	return 0
}

func (x *AlertPolicy) GetHighConsecutiveMins() int32 {
	if x != nil {
		return x.HighConsecutiveMins
	}
	return 0
}

func (x *AlertPolicy) GetSuspectTooLongSec() int64 {
	if x != nil {
		return x.SuspectTooLongSec
	}
	return 0
}

type GetAlertPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertPolicyRequest) Reset() {
	*x = GetAlertPolicyRequest{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertPolicyRequest) ProtoMessage() {}

func (x *GetAlertPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetAlertPolicyRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{16}
}

type GetAlertPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *AlertPolicy           `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertPolicyResponse) Reset() {
	*x = GetAlertPolicyResponse{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertPolicyResponse) ProtoMessage() {}

func (x *GetAlertPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetAlertPolicyResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{17}
}

func (x *GetAlertPolicyResponse) GetPolicy() *AlertPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type PutAlertPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MutationMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Policy        *AlertPolicy           `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAlertPolicyRequest) Reset() {
	*x = PutAlertPolicyRequest{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAlertPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAlertPolicyRequest) ProtoMessage() {}

func (x *PutAlertPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAlertPolicyRequest.ProtoReflect.Descriptor instead.
func (*PutAlertPolicyRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{18}
}

func (x *PutAlertPolicyRequest) GetMeta() *MutationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PutAlertPolicyRequest) GetPolicy() *AlertPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type PutAlertPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *AlertPolicy           `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAlertPolicyResponse) Reset() {
	*x = PutAlertPolicyResponse{}
	mi := &file_procmesh_v1_alert_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAlertPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAlertPolicyResponse) ProtoMessage() {}

func (x *PutAlertPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_alert_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAlertPolicyResponse.ProtoReflect.Descriptor instead.
func (*PutAlertPolicyResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_alert_proto_rawDescGZIP(), []int{19}
}

func (x *PutAlertPolicyResponse) GetPolicy() *AlertPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

var File_procmesh_v1_alert_proto protoreflect.FileDescriptor

const file_procmesh_v1_alert_proto_rawDesc = "" +
	"\n" +
	"\x17procmesh/v1/alert.proto\x12\vprocmesh.v1\x1a\x1aprocmesh/v1/mutation.proto\"\x9e\x03\n" +
	"\x05Alert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x06 \x01(\tR\tprocessId\x12!\n" +
	"\fpayload_json\x18\a \x01(\tR\vpayloadJson\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\x12\"\n" +
	"\rfirst_unix_ms\x18\t \x01(\x03R\vfirstUnixMs\x12 \n" +
	"\flast_unix_ms\x18\n" +
	" \x01(\x03R\n" +
	"lastUnixMs\x12(\n" +
	"\x10notified_unix_ms\x18\v \x01(\x03R\x0enotifiedUnixMs\x12(\n" +
	"\x10resolved_unix_ms\x18\f \x01(\x03R\x0eresolvedUnixMs\x12\x1d\n" +
	"\n" +
	"last_error\x18\r \x01(\tR\tlastError\"\xa6\x01\n" +
	"\n" +
	"AlertEntry\x12(\n" +
	"\x05alert\x18\x01 \x01(\v2\x12.procmesh.v1.AlertR\x05alert\x12\x1f\n" +
	"\vsource_node\x18\x02 \x01(\tR\n" +
	"sourceNode\x12\x1c\n" +
	"\tfreshness\x18\x03 \x01(\tR\tfreshness\x12/\n" +
	"\x14last_updated_unix_ms\x18\x04 \x01(\x03R\x11lastUpdatedUnixMs\"`\n" +
	"\x11ListAlertsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtarget_node\x18\x02 \x01(\tR\n" +
	"targetNode\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"G\n" +
	"\x12ListAlertsResponse\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.procmesh.v1.AlertEntryR\aentries\",\n" +
	"\x0fGetAlertRequest\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\"A\n" +
	"\x10GetAlertResponse\x12-\n" +
	"\x05entry\x18\x01 \x01(\v2\x17.procmesh.v1.AlertEntryR\x05entry\"\xd6\x01\n" +
	"\fAlertChannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1f\n" +
	"\vconfig_json\x18\x05 \x01(\tR\n" +
	"configJson\x12!\n" +
	"\fcreated_unix\x18\x06 \x01(\x03R\vcreatedUnix\x12!\n" +
	"\fupdated_unix\x18\a \x01(\x03R\vupdatedUnix\"\x1a\n" +
	"\x18ListAlertChannelsRequest\"R\n" +
	"\x19ListAlertChannelsResponse\x125\n" +
	"\bchannels\x18\x01 \x03(\v2\x19.procmesh.v1.AlertChannelR\bchannels\"\xc9\x01\n" +
	"\x16PutAlertChannelRequest\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.procmesh.v1.MutationMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1f\n" +
	"\vconfig_json\x18\x06 \x01(\tR\n" +
	"configJson\"N\n" +
	"\x17PutAlertChannelResponse\x123\n" +
	"\achannel\x18\x01 \x01(\v2\x19.procmesh.v1.AlertChannelR\achannel\"i\n" +
	"\x19DeleteAlertChannelRequest\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.procmesh.v1.MutationMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"\x1c\n" +
	"\x1aDeleteAlertChannelResponse\"g\n" +
	"\x17TestAlertChannelRequest\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.procmesh.v1.MutationMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"\x1a\n" +
	"\x18TestAlertChannelResponse\"\xce\x02\n" +
	"\vAlertPolicy\x12(\n" +
	"\x10dedup_window_sec\x18\x01 \x01(\x03R\x0ededupWindowSec\x12*\n" +
	"\x11notify_on_resolve\x18\x02 \x01(\bR\x0fnotifyOnResolve\x12(\n" +
	"\x10cpu_high_percent\x18\x03 \x01(\x05R\x0ecpuHighPercent\x12.\n" +
	"\x13memory_high_percent\x18\x04 \x01(\x05R\x11memoryHighPercent\x12*\n" +
	"\x11disk_high_percent\x18\x05 \x01(\x05R\x0fdiskHighPercent\x122\n" +
	"\x15high_consecutive_mins\x18\x06 \x01(\x05R\x13highConsecutiveMins\x12/\n" +
	"\x14suspect_too_long_sec\x18\a \x01(\x03R\x11suspectTooLongSec\"\x17\n" +
	"\x15GetAlertPolicyRequest\"J\n" +
	"\x16GetAlertPolicyResponse\x120\n" +
	"\x06policy\x18\x01 \x01(\v2\x18.procmesh.v1.AlertPolicyR\x06policy\"x\n" +
	"\x15PutAlertPolicyRequest\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.procmesh.v1.MutationMetaR\x04meta\x120\n" +
	"\x06policy\x18\x02 \x01(\v2\x18.procmesh.v1.AlertPolicyR\x06policy\"J\n" +
	"\x16PutAlertPolicyResponse\x120\n" +
	"\x06policy\x18\x01 \x01(\v2\x18.procmesh.v1.AlertPolicyR\x06policy2\xe6\x05\n" +
	"\fAlertService\x12M\n" +
	"\n" +
	"ListAlerts\x12\x1e.procmesh.v1.ListAlertsRequest\x1a\x1f.procmesh.v1.ListAlertsResponse\x12G\n" +
	"\bGetAlert\x12\x1c.procmesh.v1.GetAlertRequest\x1a\x1d.procmesh.v1.GetAlertResponse\x12b\n" +
	"\x11ListAlertChannels\x12%.procmesh.v1.ListAlertChannelsRequest\x1a&.procmesh.v1.ListAlertChannelsResponse\x12\\\n" +
	"\x0fPutAlertChannel\x12#.procmesh.v1.PutAlertChannelRequest\x1a$.procmesh.v1.PutAlertChannelResponse\x12e\n" +
	"\x12DeleteAlertChannel\x12&.procmesh.v1.DeleteAlertChannelRequest\x1a'.procmesh.v1.DeleteAlertChannelResponse\x12_\n" +
	"\x10TestAlertChannel\x12$.procmesh.v1.TestAlertChannelRequest\x1a%.procmesh.v1.TestAlertChannelResponse\x12Y\n" +
	"\x0eGetAlertPolicy\x12\".procmesh.v1.GetAlertPolicyRequest\x1a#.procmesh.v1.GetAlertPolicyResponse\x12Y\n" +
	"\x0ePutAlertPolicy\x12\".procmesh.v1.PutAlertPolicyRequest\x1a#.procmesh.v1.PutAlertPolicyResponseB;Z9github.com/qleelulu/procmesh/proto/procmesh/v1;procmeshv1b\x06proto3"

var (
	file_procmesh_v1_alert_proto_rawDescOnce sync.Once
	file_procmesh_v1_alert_proto_rawDescData []byte
)

func file_procmesh_v1_alert_proto_rawDescGZIP() []byte {
	file_procmesh_v1_alert_proto_rawDescOnce.Do(func() {
		file_procmesh_v1_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_procmesh_v1_alert_proto_rawDesc), len(file_procmesh_v1_alert_proto_rawDesc)))
	})
	return file_procmesh_v1_alert_proto_rawDescData
}

var file_procmesh_v1_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_procmesh_v1_alert_proto_goTypes = []any{
	(*Alert)(nil),                      // 0: procmesh.v1.Alert
	(*AlertEntry)(nil),                 // 1: procmesh.v1.AlertEntry
	(*ListAlertsRequest)(nil),          // 2: procmesh.v1.ListAlertsRequest
	(*ListAlertsResponse)(nil),         // 3: procmesh.v1.ListAlertsResponse
	(*GetAlertRequest)(nil),            // 4: procmesh.v1.GetAlertRequest
	(*GetAlertResponse)(nil),           // 5: procmesh.v1.GetAlertResponse
	(*AlertChannel)(nil),               // 6: procmesh.v1.AlertChannel
	(*ListAlertChannelsRequest)(nil),   // 7: procmesh.v1.ListAlertChannelsRequest
	(*ListAlertChannelsResponse)(nil),  // 8: procmesh.v1.ListAlertChannelsResponse
	(*PutAlertChannelRequest)(nil),     // 9: procmesh.v1.PutAlertChannelRequest
	(*PutAlertChannelResponse)(nil),    // 10: procmesh.v1.PutAlertChannelResponse
	(*DeleteAlertChannelRequest)(nil),  // 11: procmesh.v1.DeleteAlertChannelRequest
	(*DeleteAlertChannelResponse)(nil), // 12: procmesh.v1.DeleteAlertChannelResponse
	(*TestAlertChannelRequest)(nil),    // 13: procmesh.v1.TestAlertChannelRequest
	(*TestAlertChannelResponse)(nil),   // 14: procmesh.v1.TestAlertChannelResponse
	(*AlertPolicy)(nil),                // 15: procmesh.v1.AlertPolicy
	(*GetAlertPolicyRequest)(nil),      // 16: procmesh.v1.GetAlertPolicyRequest
	(*GetAlertPolicyResponse)(nil),     // 17: procmesh.v1.GetAlertPolicyResponse
	(*PutAlertPolicyRequest)(nil),      // 18: procmesh.v1.PutAlertPolicyRequest
	(*PutAlertPolicyResponse)(nil),     // 19: procmesh.v1.PutAlertPolicyResponse
	(*MutationMeta)(nil),               // 20: procmesh.v1.MutationMeta
}
var file_procmesh_v1_alert_proto_depIdxs = []int32{
	0,  // 0: procmesh.v1.AlertEntry.alert:type_name -> procmesh.v1.Alert
	1,  // 1: procmesh.v1.ListAlertsResponse.entries:type_name -> procmesh.v1.AlertEntry
	1,  // 2: procmesh.v1.GetAlertResponse.entry:type_name -> procmesh.v1.AlertEntry
	6,  // 3: procmesh.v1.ListAlertChannelsResponse.channels:type_name -> procmesh.v1.AlertChannel
	20, // 4: procmesh.v1.PutAlertChannelRequest.meta:type_name -> procmesh.v1.MutationMeta
	6,  // 5: procmesh.v1.PutAlertChannelResponse.channel:type_name -> procmesh.v1.AlertChannel
	20, // 6: procmesh.v1.DeleteAlertChannelRequest.meta:type_name -> procmesh.v1.MutationMeta
	20, // 7: procmesh.v1.TestAlertChannelRequest.meta:type_name -> procmesh.v1.MutationMeta
	15, // 8: procmesh.v1.GetAlertPolicyResponse.policy:type_name -> procmesh.v1.AlertPolicy
	20, // 9: procmesh.v1.PutAlertPolicyRequest.meta:type_name -> procmesh.v1.MutationMeta
	15, // 10: procmesh.v1.PutAlertPolicyRequest.policy:type_name -> procmesh.v1.AlertPolicy
	15, // 11: procmesh.v1.PutAlertPolicyResponse.policy:type_name -> procmesh.v1.AlertPolicy
	2,  // 12: procmesh.v1.AlertService.ListAlerts:input_type -> procmesh.v1.ListAlertsRequest
	4,  // 13: procmesh.v1.AlertService.GetAlert:input_type -> procmesh.v1.GetAlertRequest
	7,  // 14: procmesh.v1.AlertService.ListAlertChannels:input_type -> procmesh.v1.ListAlertChannelsRequest
	9,  // 15: procmesh.v1.AlertService.PutAlertChannel:input_type -> procmesh.v1.PutAlertChannelRequest
	11, // 16: procmesh.v1.AlertService.DeleteAlertChannel:input_type -> procmesh.v1.DeleteAlertChannelRequest
	13, // 17: procmesh.v1.AlertService.TestAlertChannel:input_type -> procmesh.v1.TestAlertChannelRequest
	16, // 18: procmesh.v1.AlertService.GetAlertPolicy:input_type -> procmesh.v1.GetAlertPolicyRequest
	18, // 19: procmesh.v1.AlertService.PutAlertPolicy:input_type -> procmesh.v1.PutAlertPolicyRequest
	3,  // 20: procmesh.v1.AlertService.ListAlerts:output_type -> procmesh.v1.ListAlertsResponse
	5,  // 21: procmesh.v1.AlertService.GetAlert:output_type -> procmesh.v1.GetAlertResponse
	8,  // 22: procmesh.v1.AlertService.ListAlertChannels:output_type -> procmesh.v1.ListAlertChannelsResponse
	10, // 23: procmesh.v1.AlertService.PutAlertChannel:output_type -> procmesh.v1.PutAlertChannelResponse
	12, // 24: procmesh.v1.AlertService.DeleteAlertChannel:output_type -> procmesh.v1.DeleteAlertChannelResponse
	14, // 25: procmesh.v1.AlertService.TestAlertChannel:output_type -> procmesh.v1.TestAlertChannelResponse
	17, // 26: procmesh.v1.AlertService.GetAlertPolicy:output_type -> procmesh.v1.GetAlertPolicyResponse
	19, // 27: procmesh.v1.AlertService.PutAlertPolicy:output_type -> procmesh.v1.PutAlertPolicyResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_procmesh_v1_alert_proto_init() }
func file_procmesh_v1_alert_proto_init() {
	if File_procmesh_v1_alert_proto != nil {
		return
	}
	file_procmesh_v1_mutation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_procmesh_v1_alert_proto_rawDesc), len(file_procmesh_v1_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_procmesh_v1_alert_proto_goTypes,
		DependencyIndexes: file_procmesh_v1_alert_proto_depIdxs,
		MessageInfos:      file_procmesh_v1_alert_proto_msgTypes,
	}.Build()
	File_procmesh_v1_alert_proto = out.File
	file_procmesh_v1_alert_proto_goTypes = nil
	file_procmesh_v1_alert_proto_depIdxs = nil
}
