// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: procmesh/v1/audit.proto

package procmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuditId         string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username        string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	SourceIp        string                 `protobuf:"bytes,5,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourceAgent     string                 `protobuf:"bytes,6,opt,name=source_agent,json=sourceAgent,proto3" json:"source_agent,omitempty"`
	TargetAgent     string                 `protobuf:"bytes,7,opt,name=target_agent,json=targetAgent,proto3" json:"target_agent,omitempty"`
	Resource        string                 `protobuf:"bytes,8,opt,name=resource,proto3" json:"resource,omitempty"`
	Action          string                 `protobuf:"bytes,9,opt,name=action,proto3" json:"action,omitempty"`
	OperationId     string                 `protobuf:"bytes,10,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Result          string                 `protobuf:"bytes,11,opt,name=result,proto3" json:"result,omitempty"`
	MetadataJson    string                 `protobuf:"bytes,12,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_procmesh_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEvent) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *AuditEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *AuditEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuditEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *AuditEvent) GetSourceAgent() string {
	if x != nil {
		return x.SourceAgent
	}
	return ""
}

func (x *AuditEvent) GetTargetAgent() string {
	if x != nil {
		return x.TargetAgent
	}
	return ""
}

func (x *AuditEvent) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *AuditEvent) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AuditEvent) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type AuditEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Event             *AuditEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	SourceNode        string                 `protobuf:"bytes,2,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	Freshness         string                 `protobuf:"bytes,3,opt,name=freshness,proto3" json:"freshness,omitempty"` // LIVE | STALE | UNKNOWN
	LastUpdatedUnixMs int64                  `protobuf:"varint,4,opt,name=last_updated_unix_ms,json=lastUpdatedUnixMs,proto3" json:"last_updated_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_procmesh_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *AuditEntry) GetEvent() *AuditEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AuditEntry) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *AuditEntry) GetFreshness() string {
	if x != nil {
		return x.Freshness
	}
	return ""
}

func (x *AuditEntry) GetLastUpdatedUnixMs() int64 {
	if x != nil {
		return x.LastUpdatedUnixMs
	}
	return 0
}

type ListAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`                       // 空 = 全部
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                            // 每页数量：0 = 50；封顶 200
	TargetNode    string                 `protobuf:"bytes,3,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"` // 空 = 聚合；非空 = 只查该 node
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`                              // 1-based；0 = 1；封顶 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditRequest) Reset() {
	*x = ListAuditRequest{}
	mi := &file_procmesh_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditRequest) ProtoMessage() {}

func (x *ListAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditRequest.ProtoReflect.Descriptor instead.
func (*ListAuditRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *ListAuditRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ListAuditRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuditRequest) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

func (x *ListAuditRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditResponse) Reset() {
	*x = ListAuditResponse{}
	mi := &file_procmesh_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditResponse) ProtoMessage() {}

func (x *ListAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditResponse.ProtoReflect.Descriptor instead.
func (*ListAuditResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *ListAuditResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListAuditResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAuditResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAuditResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAuditResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_procmesh_v1_audit_proto protoreflect.FileDescriptor

const file_procmesh_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x17procmesh/v1/audit.proto\x12\vprocmesh.v1\"\xff\x02\n" +
	"\n" +
	"AuditEvent\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1b\n" +
	"\tsource_ip\x18\x05 \x01(\tR\bsourceIp\x12!\n" +
	"\fsource_agent\x18\x06 \x01(\tR\vsourceAgent\x12!\n" +
	"\ftarget_agent\x18\a \x01(\tR\vtargetAgent\x12\x1a\n" +
	"\bresource\x18\b \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\t \x01(\tR\x06action\x12!\n" +
	"\foperation_id\x18\n" +
	" \x01(\tR\voperationId\x12\x16\n" +
	"\x06result\x18\v \x01(\tR\x06result\x12#\n" +
	"\rmetadata_json\x18\f \x01(\tR\fmetadataJson\"\xab\x01\n" +
	"\n" +
	"AuditEntry\x12-\n" +
	"\x05event\x18\x01 \x01(\v2\x17.procmesh.v1.AuditEventR\x05event\x12\x1f\n" +
	"\vsource_node\x18\x02 \x01(\tR\n" +
	"sourceNode\x12\x1c\n" +
	"\tfreshness\x18\x03 \x01(\tR\tfreshness\x12/\n" +
	"\x14last_updated_unix_ms\x18\x04 \x01(\x03R\x11lastUpdatedUnixMs\"y\n" +
	"\x10ListAuditRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtarget_node\x18\x03 \x01(\tR\n" +
	"targetNode\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\"\xa8\x01\n" +
	"\x11ListAuditResponse\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.procmesh.v1.AuditEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore2Z\n" +
	"\fAuditService\x12J\n" +
	"\tListAudit\x12\x1d.procmesh.v1.ListAuditRequest\x1a\x1e.procmesh.v1.ListAuditResponseB;Z9github.com/qleelulu/procmesh/proto/procmesh/v1;procmeshv1b\x06proto3"

var (
	file_procmesh_v1_audit_proto_rawDescOnce sync.Once
	file_procmesh_v1_audit_proto_rawDescData []byte
)

func file_procmesh_v1_audit_proto_rawDescGZIP() []byte {
	file_procmesh_v1_audit_proto_rawDescOnce.Do(func() {
		file_procmesh_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_procmesh_v1_audit_proto_rawDesc), len(file_procmesh_v1_audit_proto_rawDesc)))
	})
	return file_procmesh_v1_audit_proto_rawDescData
}

var file_procmesh_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_procmesh_v1_audit_proto_goTypes = []any{
	(*AuditEvent)(nil),        // 0: procmesh.v1.AuditEvent
	(*AuditEntry)(nil),        // 1: procmesh.v1.AuditEntry
	(*ListAuditRequest)(nil),  // 2: procmesh.v1.ListAuditRequest
	(*ListAuditResponse)(nil), // 3: procmesh.v1.ListAuditResponse
}
var file_procmesh_v1_audit_proto_depIdxs = []int32{
	0, // 0: procmesh.v1.AuditEntry.event:type_name -> procmesh.v1.AuditEvent
	1, // 1: procmesh.v1.ListAuditResponse.entries:type_name -> procmesh.v1.AuditEntry
	2, // 2: procmesh.v1.AuditService.ListAudit:input_type -> procmesh.v1.ListAuditRequest
	3, // 3: procmesh.v1.AuditService.ListAudit:output_type -> procmesh.v1.ListAuditResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_procmesh_v1_audit_proto_init() }
func file_procmesh_v1_audit_proto_init() {
	if File_procmesh_v1_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_procmesh_v1_audit_proto_rawDesc), len(file_procmesh_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_procmesh_v1_audit_proto_goTypes,
		DependencyIndexes: file_procmesh_v1_audit_proto_depIdxs,
		MessageInfos:      file_procmesh_v1_audit_proto_msgTypes,
	}.Build()
	File_procmesh_v1_audit_proto = out.File
	file_procmesh_v1_audit_proto_goTypes = nil
	file_procmesh_v1_audit_proto_depIdxs = nil
}
