// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: procmesh/v1/backup_types.proto

package procmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupRevisionRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	MinRevision   int64                  `protobuf:"varint,2,opt,name=min_revision,json=minRevision,proto3" json:"min_revision,omitempty"`
	MaxRevision   int64                  `protobuf:"varint,3,opt,name=max_revision,json=maxRevision,proto3" json:"max_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRevisionRange) Reset() {
	*x = BackupRevisionRange{}
	mi := &file_procmesh_v1_backup_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRevisionRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRevisionRange) ProtoMessage() {}

func (x *BackupRevisionRange) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_backup_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRevisionRange.ProtoReflect.Descriptor instead.
func (*BackupRevisionRange) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_backup_types_proto_rawDescGZIP(), []int{0}
}

func (x *BackupRevisionRange) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *BackupRevisionRange) GetMinRevision() int64 {
	if x != nil {
		return x.MinRevision
	}
	return 0
}

func (x *BackupRevisionRange) GetMaxRevision() int64 {
	if x != nil {
		return x.MaxRevision
	}
	return 0
}

type BackupSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId     string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	ClusterId      string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CreatedUnixMs  int64                  `protobuf:"varint,4,opt,name=created_unix_ms,json=createdUnixMs,proto3" json:"created_unix_ms,omitempty"`
	ProcessIds     []string               `protobuf:"bytes,5,rep,name=process_ids,json=processIds,proto3" json:"process_ids,omitempty"`
	RevisionRanges []*BackupRevisionRange `protobuf:"bytes,6,rep,name=revision_ranges,json=revisionRanges,proto3" json:"revision_ranges,omitempty"`
	Sha256         string                 `protobuf:"bytes,7,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Sink           string                 `protobuf:"bytes,8,opt,name=sink,proto3" json:"sink,omitempty"`
	Location       string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	SourceNodeId   string                 `protobuf:"bytes,10,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackupSnapshot) Reset() {
	*x = BackupSnapshot{}
	mi := &file_procmesh_v1_backup_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSnapshot) ProtoMessage() {}

func (x *BackupSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_backup_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSnapshot.ProtoReflect.Descriptor instead.
func (*BackupSnapshot) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_backup_types_proto_rawDescGZIP(), []int{1}
}

func (x *BackupSnapshot) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *BackupSnapshot) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *BackupSnapshot) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BackupSnapshot) GetCreatedUnixMs() int64 {
	if x != nil {
		return x.CreatedUnixMs
	}
	return 0
}

func (x *BackupSnapshot) GetProcessIds() []string {
	if x != nil {
		return x.ProcessIds
	}
	return nil
}

func (x *BackupSnapshot) GetRevisionRanges() []*BackupRevisionRange {
	if x != nil {
		return x.RevisionRanges
	}
	return nil
}

func (x *BackupSnapshot) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *BackupSnapshot) GetSink() string {
	if x != nil {
		return x.Sink
	}
	return ""
}

func (x *BackupSnapshot) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *BackupSnapshot) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

type BackupEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Snapshot          *BackupSnapshot        `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	SourceNode        string                 `protobuf:"bytes,2,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	Freshness         string                 `protobuf:"bytes,3,opt,name=freshness,proto3" json:"freshness,omitempty"` // LIVE | STALE | UNKNOWN
	LastUpdatedUnixMs int64                  `protobuf:"varint,4,opt,name=last_updated_unix_ms,json=lastUpdatedUnixMs,proto3" json:"last_updated_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BackupEntry) Reset() {
	*x = BackupEntry{}
	mi := &file_procmesh_v1_backup_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupEntry) ProtoMessage() {}

func (x *BackupEntry) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_backup_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupEntry.ProtoReflect.Descriptor instead.
func (*BackupEntry) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_backup_types_proto_rawDescGZIP(), []int{2}
}

func (x *BackupEntry) GetSnapshot() *BackupSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *BackupEntry) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *BackupEntry) GetFreshness() string {
	if x != nil {
		return x.Freshness
	}
	return ""
}

func (x *BackupEntry) GetLastUpdatedUnixMs() int64 {
	if x != nil {
		return x.LastUpdatedUnixMs
	}
	return 0
}

type RestoreTarget struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProcessId        string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RestoreTarget) Reset() {
	*x = RestoreTarget{}
	mi := &file_procmesh_v1_backup_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreTarget) ProtoMessage() {}

func (x *RestoreTarget) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_backup_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreTarget.ProtoReflect.Descriptor instead.
func (*RestoreTarget) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_backup_types_proto_rawDescGZIP(), []int{3}
}

func (x *RestoreTarget) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *RestoreTarget) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type RestoreProcessResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // SUCCESS | CONFLICT | INVALID | NOT_FOUND | UNAVAILABLE | DENIED
	NewRevision   int64                  `protobuf:"varint,3,opt,name=new_revision,json=newRevision,proto3" json:"new_revision,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreProcessResult) Reset() {
	*x = RestoreProcessResult{}
	mi := &file_procmesh_v1_backup_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreProcessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreProcessResult) ProtoMessage() {}

func (x *RestoreProcessResult) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_backup_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreProcessResult.ProtoReflect.Descriptor instead.
func (*RestoreProcessResult) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_backup_types_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreProcessResult) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *RestoreProcessResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RestoreProcessResult) GetNewRevision() int64 {
	if x != nil {
		return x.NewRevision
	}
	return 0
}

func (x *RestoreProcessResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_procmesh_v1_backup_types_proto protoreflect.FileDescriptor

const file_procmesh_v1_backup_types_proto_rawDesc = "" +
	"\n" +
	"\x1eprocmesh/v1/backup_types.proto\x12\vprocmesh.v1\"z\n" +
	"\x13BackupRevisionRange\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12!\n" +
	"\fmin_revision\x18\x02 \x01(\x03R\vminRevision\x12!\n" +
	"\fmax_revision\x18\x03 \x01(\x03R\vmaxRevision\"\xeb\x02\n" +
	"\x0eBackupSnapshot\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12&\n" +
	"\x0fcreated_unix_ms\x18\x04 \x01(\x03R\rcreatedUnixMs\x12\x1f\n" +
	"\vprocess_ids\x18\x05 \x03(\tR\n" +
	"processIds\x12I\n" +
	"\x0frevision_ranges\x18\x06 \x03(\v2 .procmesh.v1.BackupRevisionRangeR\x0erevisionRanges\x12\x16\n" +
	"\x06sha256\x18\a \x01(\tR\x06sha256\x12\x12\n" +
	"\x04sink\x18\b \x01(\tR\x04sink\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12$\n" +
	"\x0esource_node_id\x18\n" +
	" \x01(\tR\fsourceNodeId\"\xb6\x01\n" +
	"\vBackupEntry\x127\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1b.procmesh.v1.BackupSnapshotR\bsnapshot\x12\x1f\n" +
	"\vsource_node\x18\x02 \x01(\tR\n" +
	"sourceNode\x12\x1c\n" +
	"\tfreshness\x18\x03 \x01(\tR\tfreshness\x12/\n" +
	"\x14last_updated_unix_ms\x18\x04 \x01(\x03R\x11lastUpdatedUnixMs\"[\n" +
	"\rRestoreTarget\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x03R\x10expectedRevision\"\x86\x01\n" +
	"\x14RestoreProcessResult\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fnew_revision\x18\x03 \x01(\x03R\vnewRevision\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorB;Z9github.com/qleelulu/procmesh/proto/procmesh/v1;procmeshv1b\x06proto3"

var (
	file_procmesh_v1_backup_types_proto_rawDescOnce sync.Once
	file_procmesh_v1_backup_types_proto_rawDescData []byte
)

func file_procmesh_v1_backup_types_proto_rawDescGZIP() []byte {
	file_procmesh_v1_backup_types_proto_rawDescOnce.Do(func() {
		file_procmesh_v1_backup_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_procmesh_v1_backup_types_proto_rawDesc), len(file_procmesh_v1_backup_types_proto_rawDesc)))
	})
	return file_procmesh_v1_backup_types_proto_rawDescData
}

var file_procmesh_v1_backup_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_procmesh_v1_backup_types_proto_goTypes = []any{
	(*BackupRevisionRange)(nil),  // 0: procmesh.v1.BackupRevisionRange
	(*BackupSnapshot)(nil),       // 1: procmesh.v1.BackupSnapshot
	(*BackupEntry)(nil),          // 2: procmesh.v1.BackupEntry
	(*RestoreTarget)(nil),        // 3: procmesh.v1.RestoreTarget
	(*RestoreProcessResult)(nil), // 4: procmesh.v1.RestoreProcessResult
}
var file_procmesh_v1_backup_types_proto_depIdxs = []int32{
	0, // 0: procmesh.v1.BackupSnapshot.revision_ranges:type_name -> procmesh.v1.BackupRevisionRange
	1, // 1: procmesh.v1.BackupEntry.snapshot:type_name -> procmesh.v1.BackupSnapshot
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_procmesh_v1_backup_types_proto_init() }
func file_procmesh_v1_backup_types_proto_init() {
	if File_procmesh_v1_backup_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_procmesh_v1_backup_types_proto_rawDesc), len(file_procmesh_v1_backup_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_procmesh_v1_backup_types_proto_goTypes,
		DependencyIndexes: file_procmesh_v1_backup_types_proto_depIdxs,
		MessageInfos:      file_procmesh_v1_backup_types_proto_msgTypes,
	}.Build()
	File_procmesh_v1_backup_types_proto = out.File
	file_procmesh_v1_backup_types_proto_goTypes = nil
	file_procmesh_v1_backup_types_proto_depIdxs = nil
}
