// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: procmesh/v1/batch.proto

package procmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessNameRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ProcessName   string                 `protobuf:"bytes,2,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessNameRef) Reset() {
	*x = ProcessNameRef{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessNameRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessNameRef) ProtoMessage() {}

func (x *ProcessNameRef) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessNameRef.ProtoReflect.Descriptor instead.
func (*ProcessNameRef) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessNameRef) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ProcessNameRef) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

type BatchSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessIds    []string               `protobuf:"bytes,1,rep,name=process_ids,json=processIds,proto3" json:"process_ids,omitempty"`
	ProcessNames  []*ProcessNameRef      `protobuf:"bytes,2,rep,name=process_names,json=processNames,proto3" json:"process_names,omitempty"`
	AgentGroupId  string                 `protobuf:"bytes,3,opt,name=agent_group_id,json=agentGroupId,proto3" json:"agent_group_id,omitempty"`
	ProcessGroup  string                 `protobuf:"bytes,4,opt,name=process_group,json=processGroup,proto3" json:"process_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSelector) Reset() {
	*x = BatchSelector{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSelector) ProtoMessage() {}

func (x *BatchSelector) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSelector.ProtoReflect.Descriptor instead.
func (*BatchSelector) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{1}
}

func (x *BatchSelector) GetProcessIds() []string {
	if x != nil {
		return x.ProcessIds
	}
	return nil
}

func (x *BatchSelector) GetProcessNames() []*ProcessNameRef {
	if x != nil {
		return x.ProcessNames
	}
	return nil
}

func (x *BatchSelector) GetAgentGroupId() string {
	if x != nil {
		return x.AgentGroupId
	}
	return ""
}

func (x *BatchSelector) GetProcessGroup() string {
	if x != nil {
		return x.ProcessGroup
	}
	return ""
}

type BatchSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       int32                  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Denied        int32                  `protobuf:"varint,4,opt,name=denied,proto3" json:"denied,omitempty"`
	Conflict      int32                  `protobuf:"varint,5,opt,name=conflict,proto3" json:"conflict,omitempty"`
	Unavailable   int32                  `protobuf:"varint,6,opt,name=unavailable,proto3" json:"unavailable,omitempty"`
	Invalid       int32                  `protobuf:"varint,7,opt,name=invalid,proto3" json:"invalid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSummary) Reset() {
	*x = BatchSummary{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSummary) ProtoMessage() {}

func (x *BatchSummary) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSummary.ProtoReflect.Descriptor instead.
func (*BatchSummary) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{2}
}

func (x *BatchSummary) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *BatchSummary) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BatchSummary) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *BatchSummary) GetDenied() int32 {
	if x != nil {
		return x.Denied
	}
	return 0
}

func (x *BatchSummary) GetConflict() int32 {
	if x != nil {
		return x.Conflict
	}
	return 0
}

func (x *BatchSummary) GetUnavailable() int32 {
	if x != nil {
		return x.Unavailable
	}
	return 0
}

func (x *BatchSummary) GetInvalid() int32 {
	if x != nil {
		return x.Invalid
	}
	return 0
}

type BatchTarget struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	NodeId           string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ProcessId        string                 `protobuf:"bytes,3,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	ProcessName      string                 `protobuf:"bytes,4,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // PENDING|RUNNING|SUCCESS|FAILED|TIMEOUT|DENIED|CONFLICT|UNAVAILABLE|INVALID
	Error            string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,7,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	StartedUnixMs    int64                  `protobuf:"varint,8,opt,name=started_unix_ms,json=startedUnixMs,proto3" json:"started_unix_ms,omitempty"`
	FinishedUnixMs   int64                  `protobuf:"varint,9,opt,name=finished_unix_ms,json=finishedUnixMs,proto3" json:"finished_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchTarget) Reset() {
	*x = BatchTarget{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTarget) ProtoMessage() {}

func (x *BatchTarget) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTarget.ProtoReflect.Descriptor instead.
func (*BatchTarget) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{3}
}

func (x *BatchTarget) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *BatchTarget) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BatchTarget) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *BatchTarget) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *BatchTarget) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BatchTarget) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BatchTarget) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *BatchTarget) GetStartedUnixMs() int64 {
	if x != nil {
		return x.StartedUnixMs
	}
	return 0
}

func (x *BatchTarget) GetFinishedUnixMs() int64 {
	if x != nil {
		return x.FinishedUnixMs
	}
	return 0
}

type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	SourceAgent   string                 `protobuf:"bytes,3,opt,name=source_agent,json=sourceAgent,proto3" json:"source_agent,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // START|STOP|RESTART|CONFIG_UPDATE
	Selector      *BatchSelector         `protobuf:"bytes,5,opt,name=selector,proto3" json:"selector,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // PENDING|RUNNING|COMPLETED|PARTIAL|FAILED
	Summary       *BatchSummary          `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	CreatedUnixMs int64                  `protobuf:"varint,8,opt,name=created_unix_ms,json=createdUnixMs,proto3" json:"created_unix_ms,omitempty"`
	Targets       []*BatchTarget         `protobuf:"bytes,9,rep,name=targets,proto3" json:"targets,omitempty"` // List 可省略；Get 必填
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{4}
}

func (x *Batch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *Batch) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Batch) GetSourceAgent() string {
	if x != nil {
		return x.SourceAgent
	}
	return ""
}

func (x *Batch) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Batch) GetSelector() *BatchSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *Batch) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Batch) GetSummary() *BatchSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *Batch) GetCreatedUnixMs() int64 {
	if x != nil {
		return x.CreatedUnixMs
	}
	return 0
}

func (x *Batch) GetTargets() []*BatchTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type CreateBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MutationMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Selector      *BatchSelector         `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	Config        *ProcessSpec           `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"` // CONFIG_UPDATE required
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBatchRequest) Reset() {
	*x = CreateBatchRequest{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatchRequest) ProtoMessage() {}

func (x *CreateBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateBatchRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBatchRequest) GetMeta() *MutationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CreateBatchRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateBatchRequest) GetSelector() *BatchSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *CreateBatchRequest) GetConfig() *ProcessSpec {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateBatchRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CreateBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         *Batch                 `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBatchResponse) Reset() {
	*x = CreateBatchResponse{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatchResponse) ProtoMessage() {}

func (x *CreateBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatchResponse.ProtoReflect.Descriptor instead.
func (*CreateBatchResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBatchResponse) GetBatch() *Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

type GetBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchRequest) Reset() {
	*x = GetBatchRequest{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchRequest) ProtoMessage() {}

func (x *GetBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchRequest.ProtoReflect.Descriptor instead.
func (*GetBatchRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{7}
}

func (x *GetBatchRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type GetBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         *Batch                 `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchResponse) Reset() {
	*x = GetBatchResponse{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchResponse) ProtoMessage() {}

func (x *GetBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchResponse.ProtoReflect.Descriptor instead.
func (*GetBatchResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{8}
}

func (x *GetBatchResponse) GetBatch() *Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

type ListBatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBatchesRequest) Reset() {
	*x = ListBatchesRequest{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBatchesRequest) ProtoMessage() {}

func (x *ListBatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBatchesRequest.ProtoReflect.Descriptor instead.
func (*ListBatchesRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{9}
}

func (x *ListBatchesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListBatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batches       []*Batch               `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBatchesResponse) Reset() {
	*x = ListBatchesResponse{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBatchesResponse) ProtoMessage() {}

func (x *ListBatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBatchesResponse.ProtoReflect.Descriptor instead.
func (*ListBatchesResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{10}
}

func (x *ListBatchesResponse) GetBatches() []*Batch {
	if x != nil {
		return x.Batches
	}
	return nil
}

type RetryBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MutationMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	BatchId       string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryBatchRequest) Reset() {
	*x = RetryBatchRequest{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryBatchRequest) ProtoMessage() {}

func (x *RetryBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryBatchRequest.ProtoReflect.Descriptor instead.
func (*RetryBatchRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{11}
}

func (x *RetryBatchRequest) GetMeta() *MutationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *RetryBatchRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type RetryBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         *Batch                 `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryBatchResponse) Reset() {
	*x = RetryBatchResponse{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryBatchResponse) ProtoMessage() {}

func (x *RetryBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryBatchResponse.ProtoReflect.Descriptor instead.
func (*RetryBatchResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{12}
}

func (x *RetryBatchResponse) GetBatch() *Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

type ExportBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // json（默认）| csv
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportBatchRequest) Reset() {
	*x = ExportBatchRequest{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportBatchRequest) ProtoMessage() {}

func (x *ExportBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportBatchRequest.ProtoReflect.Descriptor instead.
func (*ExportBatchRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{13}
}

func (x *ExportBatchRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *ExportBatchRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ExportBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportBatchResponse) Reset() {
	*x = ExportBatchResponse{}
	mi := &file_procmesh_v1_batch_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportBatchResponse) ProtoMessage() {}

func (x *ExportBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_batch_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportBatchResponse.ProtoReflect.Descriptor instead.
func (*ExportBatchResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_batch_proto_rawDescGZIP(), []int{14}
}

func (x *ExportBatchResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ExportBatchResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExportBatchResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_procmesh_v1_batch_proto protoreflect.FileDescriptor

const file_procmesh_v1_batch_proto_rawDesc = "" +
	"\n" +
	"\x17procmesh/v1/batch.proto\x12\vprocmesh.v1\x1a\x1aprocmesh/v1/mutation.proto\x1a\x1fprocmesh/v1/process_types.proto\"L\n" +
	"\x0eProcessNameRef\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fprocess_name\x18\x02 \x01(\tR\vprocessName\"\xbd\x01\n" +
	"\rBatchSelector\x12\x1f\n" +
	"\vprocess_ids\x18\x01 \x03(\tR\n" +
	"processIds\x12@\n" +
	"\rprocess_names\x18\x02 \x03(\v2\x1b.procmesh.v1.ProcessNameRefR\fprocessNames\x12$\n" +
	"\x0eagent_group_id\x18\x03 \x01(\tR\fagentGroupId\x12#\n" +
	"\rprocess_group\x18\x04 \x01(\tR\fprocessGroup\"\xca\x01\n" +
	"\fBatchSummary\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\x05R\asuccess\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\x12\x16\n" +
	"\x06denied\x18\x04 \x01(\x05R\x06denied\x12\x1a\n" +
	"\bconflict\x18\x05 \x01(\x05R\bconflict\x12 \n" +
	"\vunavailable\x18\x06 \x01(\x05R\vunavailable\x12\x18\n" +
	"\ainvalid\x18\a \x01(\x05R\ainvalid\"\xb8\x02\n" +
	"\vBatchTarget\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x03 \x01(\tR\tprocessId\x12!\n" +
	"\fprocess_name\x18\x04 \x01(\tR\vprocessName\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12+\n" +
	"\x11expected_revision\x18\a \x01(\x03R\x10expectedRevision\x12&\n" +
	"\x0fstarted_unix_ms\x18\b \x01(\x03R\rstartedUnixMs\x12(\n" +
	"\x10finished_unix_ms\x18\t \x01(\x03R\x0efinishedUnixMs\"\xd6\x02\n" +
	"\x05Batch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12!\n" +
	"\fsource_agent\x18\x03 \x01(\tR\vsourceAgent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x126\n" +
	"\bselector\x18\x05 \x01(\v2\x1a.procmesh.v1.BatchSelectorR\bselector\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x123\n" +
	"\asummary\x18\a \x01(\v2\x19.procmesh.v1.BatchSummaryR\asummary\x12&\n" +
	"\x0fcreated_unix_ms\x18\b \x01(\x03R\rcreatedUnixMs\x122\n" +
	"\atargets\x18\t \x03(\v2\x18.procmesh.v1.BatchTargetR\atargets\"\xdb\x01\n" +
	"\x12CreateBatchRequest\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.procmesh.v1.MutationMetaR\x04meta\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x126\n" +
	"\bselector\x18\x03 \x01(\v2\x1a.procmesh.v1.BatchSelectorR\bselector\x120\n" +
	"\x06config\x18\x04 \x01(\v2\x18.procmesh.v1.ProcessSpecR\x06config\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\"?\n" +
	"\x13CreateBatchResponse\x12(\n" +
	"\x05batch\x18\x01 \x01(\v2\x12.procmesh.v1.BatchR\x05batch\",\n" +
	"\x0fGetBatchRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\"<\n" +
	"\x10GetBatchResponse\x12(\n" +
	"\x05batch\x18\x01 \x01(\v2\x12.procmesh.v1.BatchR\x05batch\"*\n" +
	"\x12ListBatchesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"C\n" +
	"\x13ListBatchesResponse\x12,\n" +
	"\abatches\x18\x01 \x03(\v2\x12.procmesh.v1.BatchR\abatches\"]\n" +
	"\x11RetryBatchRequest\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.procmesh.v1.MutationMetaR\x04meta\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\">\n" +
	"\x12RetryBatchResponse\x12(\n" +
	"\x05batch\x18\x01 \x01(\v2\x12.procmesh.v1.BatchR\x05batch\"G\n" +
	"\x12ExportBatchRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"n\n" +
	"\x13ExportBatchResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename2\xef\x03\n" +
	"\fBatchService\x12P\n" +
	"\vCreateBatch\x12\x1f.procmesh.v1.CreateBatchRequest\x1a .procmesh.v1.CreateBatchResponse\x12G\n" +
	"\bGetBatch\x12\x1c.procmesh.v1.GetBatchRequest\x1a\x1d.procmesh.v1.GetBatchResponse\x12P\n" +
	"\vListBatches\x12\x1f.procmesh.v1.ListBatchesRequest\x1a .procmesh.v1.ListBatchesResponse\x12N\n" +
	"\vRetryFailed\x12\x1e.procmesh.v1.RetryBatchRequest\x1a\x1f.procmesh.v1.RetryBatchResponse\x12P\n" +
	"\rReplayTimeout\x12\x1e.procmesh.v1.RetryBatchRequest\x1a\x1f.procmesh.v1.RetryBatchResponse\x12P\n" +
	"\vExportBatch\x12\x1f.procmesh.v1.ExportBatchRequest\x1a .procmesh.v1.ExportBatchResponseB;Z9github.com/qleelulu/procmesh/proto/procmesh/v1;procmeshv1b\x06proto3"

var (
	file_procmesh_v1_batch_proto_rawDescOnce sync.Once
	file_procmesh_v1_batch_proto_rawDescData []byte
)

func file_procmesh_v1_batch_proto_rawDescGZIP() []byte {
	file_procmesh_v1_batch_proto_rawDescOnce.Do(func() {
		file_procmesh_v1_batch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_procmesh_v1_batch_proto_rawDesc), len(file_procmesh_v1_batch_proto_rawDesc)))
	})
	return file_procmesh_v1_batch_proto_rawDescData
}

var file_procmesh_v1_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_procmesh_v1_batch_proto_goTypes = []any{
	(*ProcessNameRef)(nil),      // 0: procmesh.v1.ProcessNameRef
	(*BatchSelector)(nil),       // 1: procmesh.v1.BatchSelector
	(*BatchSummary)(nil),        // 2: procmesh.v1.BatchSummary
	(*BatchTarget)(nil),         // 3: procmesh.v1.BatchTarget
	(*Batch)(nil),               // 4: procmesh.v1.Batch
	(*CreateBatchRequest)(nil),  // 5: procmesh.v1.CreateBatchRequest
	(*CreateBatchResponse)(nil), // 6: procmesh.v1.CreateBatchResponse
	(*GetBatchRequest)(nil),     // 7: procmesh.v1.GetBatchRequest
	(*GetBatchResponse)(nil),    // 8: procmesh.v1.GetBatchResponse
	(*ListBatchesRequest)(nil),  // 9: procmesh.v1.ListBatchesRequest
	(*ListBatchesResponse)(nil), // 10: procmesh.v1.ListBatchesResponse
	(*RetryBatchRequest)(nil),   // 11: procmesh.v1.RetryBatchRequest
	(*RetryBatchResponse)(nil),  // 12: procmesh.v1.RetryBatchResponse
	(*ExportBatchRequest)(nil),  // 13: procmesh.v1.ExportBatchRequest
	(*ExportBatchResponse)(nil), // 14: procmesh.v1.ExportBatchResponse
	(*MutationMeta)(nil),        // 15: procmesh.v1.MutationMeta
	(*ProcessSpec)(nil),         // 16: procmesh.v1.ProcessSpec
}
var file_procmesh_v1_batch_proto_depIdxs = []int32{
	0,  // 0: procmesh.v1.BatchSelector.process_names:type_name -> procmesh.v1.ProcessNameRef
	1,  // 1: procmesh.v1.Batch.selector:type_name -> procmesh.v1.BatchSelector
	2,  // 2: procmesh.v1.Batch.summary:type_name -> procmesh.v1.BatchSummary
	3,  // 3: procmesh.v1.Batch.targets:type_name -> procmesh.v1.BatchTarget
	15, // 4: procmesh.v1.CreateBatchRequest.meta:type_name -> procmesh.v1.MutationMeta
	1,  // 5: procmesh.v1.CreateBatchRequest.selector:type_name -> procmesh.v1.BatchSelector
	16, // 6: procmesh.v1.CreateBatchRequest.config:type_name -> procmesh.v1.ProcessSpec
	4,  // 7: procmesh.v1.CreateBatchResponse.batch:type_name -> procmesh.v1.Batch
	4,  // 8: procmesh.v1.GetBatchResponse.batch:type_name -> procmesh.v1.Batch
	4,  // 9: procmesh.v1.ListBatchesResponse.batches:type_name -> procmesh.v1.Batch
	15, // 10: procmesh.v1.RetryBatchRequest.meta:type_name -> procmesh.v1.MutationMeta
	4,  // 11: procmesh.v1.RetryBatchResponse.batch:type_name -> procmesh.v1.Batch
	5,  // 12: procmesh.v1.BatchService.CreateBatch:input_type -> procmesh.v1.CreateBatchRequest
	7,  // 13: procmesh.v1.BatchService.GetBatch:input_type -> procmesh.v1.GetBatchRequest
	9,  // 14: procmesh.v1.BatchService.ListBatches:input_type -> procmesh.v1.ListBatchesRequest
	11, // 15: procmesh.v1.BatchService.RetryFailed:input_type -> procmesh.v1.RetryBatchRequest
	11, // 16: procmesh.v1.BatchService.ReplayTimeout:input_type -> procmesh.v1.RetryBatchRequest
	13, // 17: procmesh.v1.BatchService.ExportBatch:input_type -> procmesh.v1.ExportBatchRequest
	6,  // 18: procmesh.v1.BatchService.CreateBatch:output_type -> procmesh.v1.CreateBatchResponse
	8,  // 19: procmesh.v1.BatchService.GetBatch:output_type -> procmesh.v1.GetBatchResponse
	10, // 20: procmesh.v1.BatchService.ListBatches:output_type -> procmesh.v1.ListBatchesResponse
	12, // 21: procmesh.v1.BatchService.RetryFailed:output_type -> procmesh.v1.RetryBatchResponse
	12, // 22: procmesh.v1.BatchService.ReplayTimeout:output_type -> procmesh.v1.RetryBatchResponse
	14, // 23: procmesh.v1.BatchService.ExportBatch:output_type -> procmesh.v1.ExportBatchResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_procmesh_v1_batch_proto_init() }
func file_procmesh_v1_batch_proto_init() {
	if File_procmesh_v1_batch_proto != nil {
		return
	}
	file_procmesh_v1_mutation_proto_init()
	file_procmesh_v1_process_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_procmesh_v1_batch_proto_rawDesc), len(file_procmesh_v1_batch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_procmesh_v1_batch_proto_goTypes,
		DependencyIndexes: file_procmesh_v1_batch_proto_depIdxs,
		MessageInfos:      file_procmesh_v1_batch_proto_msgTypes,
	}.Build()
	File_procmesh_v1_batch_proto = out.File
	file_procmesh_v1_batch_proto_goTypes = nil
	file_procmesh_v1_batch_proto_depIdxs = nil
}
