// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: procmesh/v1/cluster_backup_agent.proto

package procmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunClusterBackupTaskRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RunId              string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskId             string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NodeId             string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PolicyRevision     int64                  `protobuf:"varint,4,opt,name=policy_revision,json=policyRevision,proto3" json:"policy_revision,omitempty"`
	Sink               string                 `protobuf:"bytes,5,opt,name=sink,proto3" json:"sink,omitempty"`
	DestinationProfile string                 `protobuf:"bytes,6,opt,name=destination_profile,json=destinationProfile,proto3" json:"destination_profile,omitempty"`
	PolicyId           string                 `protobuf:"bytes,7,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	LeaderTerm         uint64                 `protobuf:"varint,8,opt,name=leader_term,json=leaderTerm,proto3" json:"leader_term,omitempty"`
	LeaseExpiresUnix   int64                  `protobuf:"varint,9,opt,name=lease_expires_unix,json=leaseExpiresUnix,proto3" json:"lease_expires_unix,omitempty"`
	ProcessIds         []string               `protobuf:"bytes,10,rep,name=process_ids,json=processIds,proto3" json:"process_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunClusterBackupTaskRequest) Reset() {
	*x = RunClusterBackupTaskRequest{}
	mi := &file_procmesh_v1_cluster_backup_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunClusterBackupTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunClusterBackupTaskRequest) ProtoMessage() {}

func (x *RunClusterBackupTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_cluster_backup_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunClusterBackupTaskRequest.ProtoReflect.Descriptor instead.
func (*RunClusterBackupTaskRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_cluster_backup_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RunClusterBackupTaskRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunClusterBackupTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RunClusterBackupTaskRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RunClusterBackupTaskRequest) GetPolicyRevision() int64 {
	if x != nil {
		return x.PolicyRevision
	}
	return 0
}

func (x *RunClusterBackupTaskRequest) GetSink() string {
	if x != nil {
		return x.Sink
	}
	return ""
}

func (x *RunClusterBackupTaskRequest) GetDestinationProfile() string {
	if x != nil {
		return x.DestinationProfile
	}
	return ""
}

func (x *RunClusterBackupTaskRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *RunClusterBackupTaskRequest) GetLeaderTerm() uint64 {
	if x != nil {
		return x.LeaderTerm
	}
	return 0
}

func (x *RunClusterBackupTaskRequest) GetLeaseExpiresUnix() int64 {
	if x != nil {
		return x.LeaseExpiresUnix
	}
	return 0
}

func (x *RunClusterBackupTaskRequest) GetProcessIds() []string {
	if x != nil {
		return x.ProcessIds
	}
	return nil
}

type RunClusterBackupTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *ClusterBackupTask     `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunClusterBackupTaskResponse) Reset() {
	*x = RunClusterBackupTaskResponse{}
	mi := &file_procmesh_v1_cluster_backup_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunClusterBackupTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunClusterBackupTaskResponse) ProtoMessage() {}

func (x *RunClusterBackupTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_cluster_backup_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunClusterBackupTaskResponse.ProtoReflect.Descriptor instead.
func (*RunClusterBackupTaskResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_cluster_backup_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RunClusterBackupTaskResponse) GetTask() *ClusterBackupTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetClusterBackupTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterBackupTaskRequest) Reset() {
	*x = GetClusterBackupTaskRequest{}
	mi := &file_procmesh_v1_cluster_backup_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterBackupTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterBackupTaskRequest) ProtoMessage() {}

func (x *GetClusterBackupTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_cluster_backup_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterBackupTaskRequest.ProtoReflect.Descriptor instead.
func (*GetClusterBackupTaskRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_cluster_backup_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetClusterBackupTaskRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetClusterBackupTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetClusterBackupTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *ClusterBackupTask     `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterBackupTaskResponse) Reset() {
	*x = GetClusterBackupTaskResponse{}
	mi := &file_procmesh_v1_cluster_backup_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterBackupTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterBackupTaskResponse) ProtoMessage() {}

func (x *GetClusterBackupTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_cluster_backup_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterBackupTaskResponse.ProtoReflect.Descriptor instead.
func (*GetClusterBackupTaskResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_cluster_backup_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetClusterBackupTaskResponse) GetTask() *ClusterBackupTask {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_procmesh_v1_cluster_backup_agent_proto protoreflect.FileDescriptor

const file_procmesh_v1_cluster_backup_agent_proto_rawDesc = "" +
	"\n" +
	"&procmesh/v1/cluster_backup_agent.proto\x12\vprocmesh.v1\x1a procmesh/v1/cluster_backup.proto\"\xe1\x02\n" +
	"\x1bRunClusterBackupTaskRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12'\n" +
	"\x0fpolicy_revision\x18\x04 \x01(\x03R\x0epolicyRevision\x12\x12\n" +
	"\x04sink\x18\x05 \x01(\tR\x04sink\x12/\n" +
	"\x13destination_profile\x18\x06 \x01(\tR\x12destinationProfile\x12\x1b\n" +
	"\tpolicy_id\x18\a \x01(\tR\bpolicyId\x12\x1f\n" +
	"\vleader_term\x18\b \x01(\x04R\n" +
	"leaderTerm\x12,\n" +
	"\x12lease_expires_unix\x18\t \x01(\x03R\x10leaseExpiresUnix\x12\x1f\n" +
	"\vprocess_ids\x18\n" +
	" \x03(\tR\n" +
	"processIds\"R\n" +
	"\x1cRunClusterBackupTaskResponse\x122\n" +
	"\x04task\x18\x01 \x01(\v2\x1e.procmesh.v1.ClusterBackupTaskR\x04task\"M\n" +
	"\x1bGetClusterBackupTaskRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"R\n" +
	"\x1cGetClusterBackupTaskResponse\x122\n" +
	"\x04task\x18\x01 \x01(\v2\x1e.procmesh.v1.ClusterBackupTaskR\x04task2\xdb\x01\n" +
	"\x19ClusterBackupAgentService\x12^\n" +
	"\aRunTask\x12(.procmesh.v1.RunClusterBackupTaskRequest\x1a).procmesh.v1.RunClusterBackupTaskResponse\x12^\n" +
	"\aGetTask\x12(.procmesh.v1.GetClusterBackupTaskRequest\x1a).procmesh.v1.GetClusterBackupTaskResponseB;Z9github.com/qleelulu/procmesh/proto/procmesh/v1;procmeshv1b\x06proto3"

var (
	file_procmesh_v1_cluster_backup_agent_proto_rawDescOnce sync.Once
	file_procmesh_v1_cluster_backup_agent_proto_rawDescData []byte
)

func file_procmesh_v1_cluster_backup_agent_proto_rawDescGZIP() []byte {
	file_procmesh_v1_cluster_backup_agent_proto_rawDescOnce.Do(func() {
		file_procmesh_v1_cluster_backup_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_procmesh_v1_cluster_backup_agent_proto_rawDesc), len(file_procmesh_v1_cluster_backup_agent_proto_rawDesc)))
	})
	return file_procmesh_v1_cluster_backup_agent_proto_rawDescData
}

var file_procmesh_v1_cluster_backup_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_procmesh_v1_cluster_backup_agent_proto_goTypes = []any{
	(*RunClusterBackupTaskRequest)(nil),  // 0: procmesh.v1.RunClusterBackupTaskRequest
	(*RunClusterBackupTaskResponse)(nil), // 1: procmesh.v1.RunClusterBackupTaskResponse
	(*GetClusterBackupTaskRequest)(nil),  // 2: procmesh.v1.GetClusterBackupTaskRequest
	(*GetClusterBackupTaskResponse)(nil), // 3: procmesh.v1.GetClusterBackupTaskResponse
	(*ClusterBackupTask)(nil),            // 4: procmesh.v1.ClusterBackupTask
}
var file_procmesh_v1_cluster_backup_agent_proto_depIdxs = []int32{
	4, // 0: procmesh.v1.RunClusterBackupTaskResponse.task:type_name -> procmesh.v1.ClusterBackupTask
	4, // 1: procmesh.v1.GetClusterBackupTaskResponse.task:type_name -> procmesh.v1.ClusterBackupTask
	0, // 2: procmesh.v1.ClusterBackupAgentService.RunTask:input_type -> procmesh.v1.RunClusterBackupTaskRequest
	2, // 3: procmesh.v1.ClusterBackupAgentService.GetTask:input_type -> procmesh.v1.GetClusterBackupTaskRequest
	1, // 4: procmesh.v1.ClusterBackupAgentService.RunTask:output_type -> procmesh.v1.RunClusterBackupTaskResponse
	3, // 5: procmesh.v1.ClusterBackupAgentService.GetTask:output_type -> procmesh.v1.GetClusterBackupTaskResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_procmesh_v1_cluster_backup_agent_proto_init() }
func file_procmesh_v1_cluster_backup_agent_proto_init() {
	if File_procmesh_v1_cluster_backup_agent_proto != nil {
		return
	}
	file_procmesh_v1_cluster_backup_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_procmesh_v1_cluster_backup_agent_proto_rawDesc), len(file_procmesh_v1_cluster_backup_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_procmesh_v1_cluster_backup_agent_proto_goTypes,
		DependencyIndexes: file_procmesh_v1_cluster_backup_agent_proto_depIdxs,
		MessageInfos:      file_procmesh_v1_cluster_backup_agent_proto_msgTypes,
	}.Build()
	File_procmesh_v1_cluster_backup_agent_proto = out.File
	file_procmesh_v1_cluster_backup_agent_proto_goTypes = nil
	file_procmesh_v1_cluster_backup_agent_proto_depIdxs = nil
}
