// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: procmesh/v1/metrics.proto

package procmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAgentMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentMetricsRequest) Reset() {
	*x = GetAgentMetricsRequest{}
	mi := &file_procmesh_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentMetricsRequest) ProtoMessage() {}

func (x *GetAgentMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetAgentMetricsRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_metrics_proto_rawDescGZIP(), []int{0}
}

type AgentMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds  float64                `protobuf:"fixed64,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ProcessRunning int32                  `protobuf:"varint,2,opt,name=process_running,json=processRunning,proto3" json:"process_running,omitempty"`
	Members        int32                  `protobuf:"varint,3,opt,name=members,proto3" json:"members,omitempty"`
	Alive          int32                  `protobuf:"varint,4,opt,name=alive,proto3" json:"alive,omitempty"`
	ControlQuorum  bool                   `protobuf:"varint,5,opt,name=control_quorum,json=controlQuorum,proto3" json:"control_quorum,omitempty"`
	Resources      *ResourceSummary       `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentMetrics) Reset() {
	*x = AgentMetrics{}
	mi := &file_procmesh_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetrics) ProtoMessage() {}

func (x *AgentMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetrics.ProtoReflect.Descriptor instead.
func (*AgentMetrics) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *AgentMetrics) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *AgentMetrics) GetProcessRunning() int32 {
	if x != nil {
		return x.ProcessRunning
	}
	return 0
}

func (x *AgentMetrics) GetMembers() int32 {
	if x != nil {
		return x.Members
	}
	return 0
}

func (x *AgentMetrics) GetAlive() int32 {
	if x != nil {
		return x.Alive
	}
	return 0
}

func (x *AgentMetrics) GetControlQuorum() bool {
	if x != nil {
		return x.ControlQuorum
	}
	return false
}

func (x *AgentMetrics) GetResources() *ResourceSummary {
	if x != nil {
		return x.Resources
	}
	return nil
}

type GetAgentMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *AgentMetrics          `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentMetricsResponse) Reset() {
	*x = GetAgentMetricsResponse{}
	mi := &file_procmesh_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentMetricsResponse) ProtoMessage() {}

func (x *GetAgentMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetAgentMetricsResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentMetricsResponse) GetMetrics() *AgentMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GetProcessMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdOrName      string                 `protobuf:"bytes,1,opt,name=id_or_name,json=idOrName,proto3" json:"id_or_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessMetricsRequest) Reset() {
	*x = GetProcessMetricsRequest{}
	mi := &file_procmesh_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessMetricsRequest) ProtoMessage() {}

func (x *GetProcessMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetProcessMetricsRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *GetProcessMetricsRequest) GetIdOrName() string {
	if x != nil {
		return x.IdOrName
	}
	return ""
}

func (x *GetProcessMetricsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type ProcessMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	CpuPercent    int32                  `protobuf:"varint,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`    // -1 = unknown
	MemoryBytes   int64                  `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"` // -1 = unknown
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMetrics) Reset() {
	*x = ProcessMetrics{}
	mi := &file_procmesh_v1_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMetrics) ProtoMessage() {}

func (x *ProcessMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMetrics.ProtoReflect.Descriptor instead.
func (*ProcessMetrics) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessMetrics) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ProcessMetrics) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessMetrics) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ProcessMetrics) GetCpuPercent() int32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessMetrics) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ProcessMetrics) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type GetProcessMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*ProcessMetrics      `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessMetricsResponse) Reset() {
	*x = GetProcessMetricsResponse{}
	mi := &file_procmesh_v1_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessMetricsResponse) ProtoMessage() {}

func (x *GetProcessMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetProcessMetricsResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *GetProcessMetricsResponse) GetMetrics() []*ProcessMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUnix        int64                  `protobuf:"varint,1,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_procmesh_v1_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *MetricPoint) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

func (x *MetricPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MetricSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // cpu_percent | memory_percent | disk_percent | memory_bytes
	Layer         string                 `protobuf:"bytes,2,opt,name=layer,proto3" json:"layer,omitempty"`   // raw_min | down_5m
	Points        []*MetricPoint         `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"` // ASC；缺口省略
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSeries) Reset() {
	*x = MetricSeries{}
	mi := &file_procmesh_v1_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSeries) ProtoMessage() {}

func (x *MetricSeries) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSeries.ProtoReflect.Descriptor instead.
func (*MetricSeries) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *MetricSeries) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricSeries) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *MetricSeries) GetPoints() []*MetricPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GetNodeHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SinceUnix     int64                  `protobuf:"varint,2,opt,name=since_unix,json=sinceUnix,proto3" json:"since_unix,omitempty"`
	UntilUnix     int64                  `protobuf:"varint,3,opt,name=until_unix,json=untilUnix,proto3" json:"until_unix,omitempty"`
	Resolution    string                 `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"` // empty | raw_min | down_5m
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeHistoryRequest) Reset() {
	*x = GetNodeHistoryRequest{}
	mi := &file_procmesh_v1_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeHistoryRequest) ProtoMessage() {}

func (x *GetNodeHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetNodeHistoryRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *GetNodeHistoryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeHistoryRequest) GetSinceUnix() int64 {
	if x != nil {
		return x.SinceUnix
	}
	return 0
}

func (x *GetNodeHistoryRequest) GetUntilUnix() int64 {
	if x != nil {
		return x.UntilUnix
	}
	return 0
}

func (x *GetNodeHistoryRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

type GetNodeHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Layer         string                 `protobuf:"bytes,2,opt,name=layer,proto3" json:"layer,omitempty"`
	Series        []*MetricSeries        `protobuf:"bytes,3,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeHistoryResponse) Reset() {
	*x = GetNodeHistoryResponse{}
	mi := &file_procmesh_v1_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeHistoryResponse) ProtoMessage() {}

func (x *GetNodeHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetNodeHistoryResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *GetNodeHistoryResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeHistoryResponse) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *GetNodeHistoryResponse) GetSeries() []*MetricSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

type GetProcessHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdOrName      string                 `protobuf:"bytes,1,opt,name=id_or_name,json=idOrName,proto3" json:"id_or_name,omitempty"`
	SinceUnix     int64                  `protobuf:"varint,2,opt,name=since_unix,json=sinceUnix,proto3" json:"since_unix,omitempty"`
	UntilUnix     int64                  `protobuf:"varint,3,opt,name=until_unix,json=untilUnix,proto3" json:"until_unix,omitempty"`
	Resolution    string                 `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessHistoryRequest) Reset() {
	*x = GetProcessHistoryRequest{}
	mi := &file_procmesh_v1_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessHistoryRequest) ProtoMessage() {}

func (x *GetProcessHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetProcessHistoryRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *GetProcessHistoryRequest) GetIdOrName() string {
	if x != nil {
		return x.IdOrName
	}
	return ""
}

func (x *GetProcessHistoryRequest) GetSinceUnix() int64 {
	if x != nil {
		return x.SinceUnix
	}
	return 0
}

func (x *GetProcessHistoryRequest) GetUntilUnix() int64 {
	if x != nil {
		return x.UntilUnix
	}
	return 0
}

func (x *GetProcessHistoryRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

type GetProcessHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Layer         string                 `protobuf:"bytes,2,opt,name=layer,proto3" json:"layer,omitempty"`
	Series        []*MetricSeries        `protobuf:"bytes,3,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessHistoryResponse) Reset() {
	*x = GetProcessHistoryResponse{}
	mi := &file_procmesh_v1_metrics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessHistoryResponse) ProtoMessage() {}

func (x *GetProcessHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_metrics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetProcessHistoryResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_metrics_proto_rawDescGZIP(), []int{11}
}

func (x *GetProcessHistoryResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *GetProcessHistoryResponse) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *GetProcessHistoryResponse) GetSeries() []*MetricSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

var File_procmesh_v1_metrics_proto protoreflect.FileDescriptor

const file_procmesh_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x19procmesh/v1/metrics.proto\x12\vprocmesh.v1\x1a\x1fprocmesh/v1/cluster_types.proto\"\x18\n" +
	"\x16GetAgentMetricsRequest\"\xf1\x01\n" +
	"\fAgentMetrics\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x01R\ruptimeSeconds\x12'\n" +
	"\x0fprocess_running\x18\x02 \x01(\x05R\x0eprocessRunning\x12\x18\n" +
	"\amembers\x18\x03 \x01(\x05R\amembers\x12\x14\n" +
	"\x05alive\x18\x04 \x01(\x05R\x05alive\x12%\n" +
	"\x0econtrol_quorum\x18\x05 \x01(\bR\rcontrolQuorum\x12:\n" +
	"\tresources\x18\x06 \x01(\v2\x1c.procmesh.v1.ResourceSummaryR\tresources\"N\n" +
	"\x17GetAgentMetricsResponse\x123\n" +
	"\ametrics\x18\x01 \x01(\v2\x19.procmesh.v1.AgentMetricsR\ametrics\"Y\n" +
	"\x18GetProcessMetricsRequest\x12\x1c\n" +
	"\n" +
	"id_or_name\x18\x01 \x01(\tR\bidOrName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\"\xc2\x01\n" +
	"\x0eProcessMetrics\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\x05R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x03R\vmemoryBytes\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\"R\n" +
	"\x19GetProcessMetricsResponse\x125\n" +
	"\ametrics\x18\x01 \x03(\v2\x1b.procmesh.v1.ProcessMetricsR\ametrics\"<\n" +
	"\vMetricPoint\x12\x17\n" +
	"\ats_unix\x18\x01 \x01(\x03R\x06tsUnix\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"j\n" +
	"\fMetricSeries\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05layer\x18\x02 \x01(\tR\x05layer\x120\n" +
	"\x06points\x18\x03 \x03(\v2\x18.procmesh.v1.MetricPointR\x06points\"\x8e\x01\n" +
	"\x15GetNodeHistoryRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"since_unix\x18\x02 \x01(\x03R\tsinceUnix\x12\x1d\n" +
	"\n" +
	"until_unix\x18\x03 \x01(\x03R\tuntilUnix\x12\x1e\n" +
	"\n" +
	"resolution\x18\x04 \x01(\tR\n" +
	"resolution\"z\n" +
	"\x16GetNodeHistoryResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05layer\x18\x02 \x01(\tR\x05layer\x121\n" +
	"\x06series\x18\x03 \x03(\v2\x19.procmesh.v1.MetricSeriesR\x06series\"\x96\x01\n" +
	"\x18GetProcessHistoryRequest\x12\x1c\n" +
	"\n" +
	"id_or_name\x18\x01 \x01(\tR\bidOrName\x12\x1d\n" +
	"\n" +
	"since_unix\x18\x02 \x01(\x03R\tsinceUnix\x12\x1d\n" +
	"\n" +
	"until_unix\x18\x03 \x01(\x03R\tuntilUnix\x12\x1e\n" +
	"\n" +
	"resolution\x18\x04 \x01(\tR\n" +
	"resolution\"\x83\x01\n" +
	"\x19GetProcessHistoryResponse\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x14\n" +
	"\x05layer\x18\x02 \x01(\tR\x05layer\x121\n" +
	"\x06series\x18\x03 \x03(\v2\x19.procmesh.v1.MetricSeriesR\x06series2\x91\x03\n" +
	"\x0eMetricsService\x12\\\n" +
	"\x0fGetAgentMetrics\x12#.procmesh.v1.GetAgentMetricsRequest\x1a$.procmesh.v1.GetAgentMetricsResponse\x12b\n" +
	"\x11GetProcessMetrics\x12%.procmesh.v1.GetProcessMetricsRequest\x1a&.procmesh.v1.GetProcessMetricsResponse\x12Y\n" +
	"\x0eGetNodeHistory\x12\".procmesh.v1.GetNodeHistoryRequest\x1a#.procmesh.v1.GetNodeHistoryResponse\x12b\n" +
	"\x11GetProcessHistory\x12%.procmesh.v1.GetProcessHistoryRequest\x1a&.procmesh.v1.GetProcessHistoryResponseB;Z9github.com/qleelulu/procmesh/proto/procmesh/v1;procmeshv1b\x06proto3"

var (
	file_procmesh_v1_metrics_proto_rawDescOnce sync.Once
	file_procmesh_v1_metrics_proto_rawDescData []byte
)

func file_procmesh_v1_metrics_proto_rawDescGZIP() []byte {
	file_procmesh_v1_metrics_proto_rawDescOnce.Do(func() {
		file_procmesh_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_procmesh_v1_metrics_proto_rawDesc), len(file_procmesh_v1_metrics_proto_rawDesc)))
	})
	return file_procmesh_v1_metrics_proto_rawDescData
}

var file_procmesh_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_procmesh_v1_metrics_proto_goTypes = []any{
	(*GetAgentMetricsRequest)(nil),    // 0: procmesh.v1.GetAgentMetricsRequest
	(*AgentMetrics)(nil),              // 1: procmesh.v1.AgentMetrics
	(*GetAgentMetricsResponse)(nil),   // 2: procmesh.v1.GetAgentMetricsResponse
	(*GetProcessMetricsRequest)(nil),  // 3: procmesh.v1.GetProcessMetricsRequest
	(*ProcessMetrics)(nil),            // 4: procmesh.v1.ProcessMetrics
	(*GetProcessMetricsResponse)(nil), // 5: procmesh.v1.GetProcessMetricsResponse
	(*MetricPoint)(nil),               // 6: procmesh.v1.MetricPoint
	(*MetricSeries)(nil),              // 7: procmesh.v1.MetricSeries
	(*GetNodeHistoryRequest)(nil),     // 8: procmesh.v1.GetNodeHistoryRequest
	(*GetNodeHistoryResponse)(nil),    // 9: procmesh.v1.GetNodeHistoryResponse
	(*GetProcessHistoryRequest)(nil),  // 10: procmesh.v1.GetProcessHistoryRequest
	(*GetProcessHistoryResponse)(nil), // 11: procmesh.v1.GetProcessHistoryResponse
	(*ResourceSummary)(nil),           // 12: procmesh.v1.ResourceSummary
}
var file_procmesh_v1_metrics_proto_depIdxs = []int32{
	12, // 0: procmesh.v1.AgentMetrics.resources:type_name -> procmesh.v1.ResourceSummary
	1,  // 1: procmesh.v1.GetAgentMetricsResponse.metrics:type_name -> procmesh.v1.AgentMetrics
	4,  // 2: procmesh.v1.GetProcessMetricsResponse.metrics:type_name -> procmesh.v1.ProcessMetrics
	6,  // 3: procmesh.v1.MetricSeries.points:type_name -> procmesh.v1.MetricPoint
	7,  // 4: procmesh.v1.GetNodeHistoryResponse.series:type_name -> procmesh.v1.MetricSeries
	7,  // 5: procmesh.v1.GetProcessHistoryResponse.series:type_name -> procmesh.v1.MetricSeries
	0,  // 6: procmesh.v1.MetricsService.GetAgentMetrics:input_type -> procmesh.v1.GetAgentMetricsRequest
	3,  // 7: procmesh.v1.MetricsService.GetProcessMetrics:input_type -> procmesh.v1.GetProcessMetricsRequest
	8,  // 8: procmesh.v1.MetricsService.GetNodeHistory:input_type -> procmesh.v1.GetNodeHistoryRequest
	10, // 9: procmesh.v1.MetricsService.GetProcessHistory:input_type -> procmesh.v1.GetProcessHistoryRequest
	2,  // 10: procmesh.v1.MetricsService.GetAgentMetrics:output_type -> procmesh.v1.GetAgentMetricsResponse
	5,  // 11: procmesh.v1.MetricsService.GetProcessMetrics:output_type -> procmesh.v1.GetProcessMetricsResponse
	9,  // 12: procmesh.v1.MetricsService.GetNodeHistory:output_type -> procmesh.v1.GetNodeHistoryResponse
	11, // 13: procmesh.v1.MetricsService.GetProcessHistory:output_type -> procmesh.v1.GetProcessHistoryResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_procmesh_v1_metrics_proto_init() }
func file_procmesh_v1_metrics_proto_init() {
	if File_procmesh_v1_metrics_proto != nil {
		return
	}
	file_procmesh_v1_cluster_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_procmesh_v1_metrics_proto_rawDesc), len(file_procmesh_v1_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_procmesh_v1_metrics_proto_goTypes,
		DependencyIndexes: file_procmesh_v1_metrics_proto_depIdxs,
		MessageInfos:      file_procmesh_v1_metrics_proto_msgTypes,
	}.Build()
	File_procmesh_v1_metrics_proto = out.File
	file_procmesh_v1_metrics_proto_goTypes = nil
	file_procmesh_v1_metrics_proto_depIdxs = nil
}
