// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: procmesh/v1/mutation.proto

package procmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MutationMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationMeta) Reset() {
	*x = MutationMeta{}
	mi := &file_procmesh_v1_mutation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationMeta) ProtoMessage() {}

func (x *MutationMeta) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_mutation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationMeta.ProtoReflect.Descriptor instead.
func (*MutationMeta) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_mutation_proto_rawDescGZIP(), []int{0}
}

func (x *MutationMeta) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *MutationMeta) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

var File_procmesh_v1_mutation_proto protoreflect.FileDescriptor

const file_procmesh_v1_mutation_proto_rawDesc = "" +
	"\n" +
	"\x1aprocmesh/v1/mutation.proto\x12\vprocmesh.v1\"M\n" +
	"\fMutationMeta\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperatorB;Z9github.com/qleelulu/procmesh/proto/procmesh/v1;procmeshv1b\x06proto3"

var (
	file_procmesh_v1_mutation_proto_rawDescOnce sync.Once
	file_procmesh_v1_mutation_proto_rawDescData []byte
)

func file_procmesh_v1_mutation_proto_rawDescGZIP() []byte {
	file_procmesh_v1_mutation_proto_rawDescOnce.Do(func() {
		file_procmesh_v1_mutation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_procmesh_v1_mutation_proto_rawDesc), len(file_procmesh_v1_mutation_proto_rawDesc)))
	})
	return file_procmesh_v1_mutation_proto_rawDescData
}

var file_procmesh_v1_mutation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_procmesh_v1_mutation_proto_goTypes = []any{
	(*MutationMeta)(nil), // 0: procmesh.v1.MutationMeta
}
var file_procmesh_v1_mutation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_procmesh_v1_mutation_proto_init() }
func file_procmesh_v1_mutation_proto_init() {
	if File_procmesh_v1_mutation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_procmesh_v1_mutation_proto_rawDesc), len(file_procmesh_v1_mutation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_procmesh_v1_mutation_proto_goTypes,
		DependencyIndexes: file_procmesh_v1_mutation_proto_depIdxs,
		MessageInfos:      file_procmesh_v1_mutation_proto_msgTypes,
	}.Build()
	File_procmesh_v1_mutation_proto = out.File
	file_procmesh_v1_mutation_proto_goTypes = nil
	file_procmesh_v1_mutation_proto_depIdxs = nil
}
