// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: procmesh/v1/peer_replication.proto

package procmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClusterId      string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	SnapshotId     string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Sha256         string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	RunId          string                 `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskId         string                 `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Payload        []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	PolicyId       string                 `protobuf:"bytes,7,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyRevision int64                  `protobuf:"varint,8,opt,name=policy_revision,json=policyRevision,proto3" json:"policy_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutSnapshotRequest) Reset() {
	*x = PutSnapshotRequest{}
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSnapshotRequest) ProtoMessage() {}

func (x *PutSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSnapshotRequest.ProtoReflect.Descriptor instead.
func (*PutSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_peer_replication_proto_rawDescGZIP(), []int{0}
}

func (x *PutSnapshotRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *PutSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *PutSnapshotRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *PutSnapshotRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *PutSnapshotRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PutSnapshotRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PutSnapshotRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PutSnapshotRequest) GetPolicyRevision() int64 {
	if x != nil {
		return x.PolicyRevision
	}
	return 0
}

type PutSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	ProcessCount  int32                  `protobuf:"varint,4,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	ProcessIds    []string               `protobuf:"bytes,5,rep,name=process_ids,json=processIds,proto3" json:"process_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutSnapshotResponse) Reset() {
	*x = PutSnapshotResponse{}
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSnapshotResponse) ProtoMessage() {}

func (x *PutSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSnapshotResponse.ProtoReflect.Descriptor instead.
func (*PutSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_peer_replication_proto_rawDescGZIP(), []int{1}
}

func (x *PutSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *PutSnapshotResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *PutSnapshotResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *PutSnapshotResponse) GetProcessCount() int32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *PutSnapshotResponse) GetProcessIds() []string {
	if x != nil {
		return x.ProcessIds
	}
	return nil
}

// ReplicateSnapshot is Leader-authorized metadata-only work sent to the
// source Agent. The source reloads the indexed payload and calls PutSnapshot
// itself, so the Leader never observes payload bytes.
type ReplicateSnapshotRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RunId            string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskId           string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	PolicyId         string                 `protobuf:"bytes,3,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyRevision   int64                  `protobuf:"varint,4,opt,name=policy_revision,json=policyRevision,proto3" json:"policy_revision,omitempty"`
	SourceNodeId     string                 `protobuf:"bytes,5,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetNodeId     string                 `protobuf:"bytes,6,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	SnapshotId       string                 `protobuf:"bytes,7,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Sha256           string                 `protobuf:"bytes,8,opt,name=sha256,proto3" json:"sha256,omitempty"`
	LeaderTerm       uint64                 `protobuf:"varint,9,opt,name=leader_term,json=leaderTerm,proto3" json:"leader_term,omitempty"`
	LeaseExpiresUnix int64                  `protobuf:"varint,10,opt,name=lease_expires_unix,json=leaseExpiresUnix,proto3" json:"lease_expires_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplicateSnapshotRequest) Reset() {
	*x = ReplicateSnapshotRequest{}
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateSnapshotRequest) ProtoMessage() {}

func (x *ReplicateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ReplicateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_peer_replication_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicateSnapshotRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ReplicateSnapshotRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReplicateSnapshotRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ReplicateSnapshotRequest) GetPolicyRevision() int64 {
	if x != nil {
		return x.PolicyRevision
	}
	return 0
}

func (x *ReplicateSnapshotRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *ReplicateSnapshotRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *ReplicateSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *ReplicateSnapshotRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ReplicateSnapshotRequest) GetLeaderTerm() uint64 {
	if x != nil {
		return x.LeaderTerm
	}
	return 0
}

func (x *ReplicateSnapshotRequest) GetLeaseExpiresUnix() int64 {
	if x != nil {
		return x.LeaseExpiresUnix
	}
	return 0
}

type ReplicateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Bytes         int64                  `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateSnapshotResponse) Reset() {
	*x = ReplicateSnapshotResponse{}
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateSnapshotResponse) ProtoMessage() {}

func (x *ReplicateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*ReplicateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_peer_replication_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicateSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *ReplicateSnapshotResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ReplicateSnapshotResponse) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type CheckSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId  string                 `protobuf:"bytes,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSnapshotRequest) Reset() {
	*x = CheckSnapshotRequest{}
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSnapshotRequest) ProtoMessage() {}

func (x *CheckSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CheckSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_peer_replication_proto_rawDescGZIP(), []int{4}
}

func (x *CheckSnapshotRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *CheckSnapshotRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *CheckSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *CheckSnapshotRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type CheckSnapshotResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Exists          bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	ChecksumMatches bool                   `protobuf:"varint,2,opt,name=checksum_matches,json=checksumMatches,proto3" json:"checksum_matches,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckSnapshotResponse) Reset() {
	*x = CheckSnapshotResponse{}
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSnapshotResponse) ProtoMessage() {}

func (x *CheckSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CheckSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_peer_replication_proto_rawDescGZIP(), []int{5}
}

func (x *CheckSnapshotResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckSnapshotResponse) GetChecksumMatches() bool {
	if x != nil {
		return x.ChecksumMatches
	}
	return false
}

type DeleteSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId   string                 `protobuf:"bytes,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	ClusterId      string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	SnapshotId     string                 `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	IntentId       string                 `protobuf:"bytes,4,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	PolicyId       string                 `protobuf:"bytes,5,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyRevision int64                  `protobuf:"varint,6,opt,name=policy_revision,json=policyRevision,proto3" json:"policy_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_peer_replication_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSnapshotRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetPolicyRevision() int64 {
	if x != nil {
		return x.PolicyRevision
	}
	return 0
}

type DeleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_peer_replication_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSnapshotResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GetReplicaMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId  string                 `protobuf:"bytes,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicaMetadataRequest) Reset() {
	*x = GetReplicaMetadataRequest{}
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicaMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicaMetadataRequest) ProtoMessage() {}

func (x *GetReplicaMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicaMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetReplicaMetadataRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_peer_replication_proto_rawDescGZIP(), []int{8}
}

func (x *GetReplicaMetadataRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *GetReplicaMetadataRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *GetReplicaMetadataRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type GetReplicaMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ProcessCount  int32                  `protobuf:"varint,6,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	ProcessIds    []string               `protobuf:"bytes,7,rep,name=process_ids,json=processIds,proto3" json:"process_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicaMetadataResponse) Reset() {
	*x = GetReplicaMetadataResponse{}
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicaMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicaMetadataResponse) ProtoMessage() {}

func (x *GetReplicaMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicaMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetReplicaMetadataResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_peer_replication_proto_rawDescGZIP(), []int{9}
}

func (x *GetReplicaMetadataResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *GetReplicaMetadataResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *GetReplicaMetadataResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetReplicaMetadataResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *GetReplicaMetadataResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetReplicaMetadataResponse) GetProcessCount() int32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *GetReplicaMetadataResponse) GetProcessIds() []string {
	if x != nil {
		return x.ProcessIds
	}
	return nil
}

// FetchSnapshot is an internal mTLS-only pull used by the source Owner during
// disaster recovery. The requester certificate must identify source_node_id.
type FetchSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId  string                 `protobuf:"bytes,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSnapshotRequest) Reset() {
	*x = FetchSnapshotRequest{}
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSnapshotRequest) ProtoMessage() {}

func (x *FetchSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSnapshotRequest.ProtoReflect.Descriptor instead.
func (*FetchSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_peer_replication_proto_rawDescGZIP(), []int{10}
}

func (x *FetchSnapshotRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *FetchSnapshotRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *FetchSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *FetchSnapshotRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type FetchSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId  string                 `protobuf:"bytes,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	ProcessIds    []string               `protobuf:"bytes,5,rep,name=process_ids,json=processIds,proto3" json:"process_ids,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSnapshotResponse) Reset() {
	*x = FetchSnapshotResponse{}
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSnapshotResponse) ProtoMessage() {}

func (x *FetchSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_peer_replication_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSnapshotResponse.ProtoReflect.Descriptor instead.
func (*FetchSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_peer_replication_proto_rawDescGZIP(), []int{11}
}

func (x *FetchSnapshotResponse) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *FetchSnapshotResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *FetchSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *FetchSnapshotResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *FetchSnapshotResponse) GetProcessIds() []string {
	if x != nil {
		return x.ProcessIds
	}
	return nil
}

func (x *FetchSnapshotResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_procmesh_v1_peer_replication_proto protoreflect.FileDescriptor

const file_procmesh_v1_peer_replication_proto_rawDesc = "" +
	"\n" +
	"\"procmesh/v1/peer_replication.proto\x12\vprocmesh.v1\"\xfc\x01\n" +
	"\x12PutSnapshotRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x05 \x01(\tR\x06taskId\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1b\n" +
	"\tpolicy_id\x18\a \x01(\tR\bpolicyId\x12'\n" +
	"\x0fpolicy_revision\x18\b \x01(\x03R\x0epolicyRevision\"\xb3\x01\n" +
	"\x13PutSnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12#\n" +
	"\rprocess_count\x18\x04 \x01(\x05R\fprocessCount\x12\x1f\n" +
	"\vprocess_ids\x18\x05 \x03(\tR\n" +
	"processIds\"\xe4\x02\n" +
	"\x18ReplicateSnapshotRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tpolicy_id\x18\x03 \x01(\tR\bpolicyId\x12'\n" +
	"\x0fpolicy_revision\x18\x04 \x01(\x03R\x0epolicyRevision\x12$\n" +
	"\x0esource_node_id\x18\x05 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x06 \x01(\tR\ftargetNodeId\x12\x1f\n" +
	"\vsnapshot_id\x18\a \x01(\tR\n" +
	"snapshotId\x12\x16\n" +
	"\x06sha256\x18\b \x01(\tR\x06sha256\x12\x1f\n" +
	"\vleader_term\x18\t \x01(\x04R\n" +
	"leaderTerm\x12,\n" +
	"\x12lease_expires_unix\x18\n" +
	" \x01(\x03R\x10leaseExpiresUnix\"j\n" +
	"\x19ReplicateSnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x03R\x05bytes\"\x94\x01\n" +
	"\x14CheckSnapshotRequest\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\tR\fsourceNodeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\tR\n" +
	"snapshotId\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\"Z\n" +
	"\x15CheckSnapshotResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12)\n" +
	"\x10checksum_matches\x18\x02 \x01(\bR\x0fchecksumMatches\"\xe0\x01\n" +
	"\x15DeleteSnapshotRequest\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\tR\fsourceNodeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\tR\n" +
	"snapshotId\x12\x1b\n" +
	"\tintent_id\x18\x04 \x01(\tR\bintentId\x12\x1b\n" +
	"\tpolicy_id\x18\x05 \x01(\tR\bpolicyId\x12'\n" +
	"\x0fpolicy_revision\x18\x06 \x01(\x03R\x0epolicyRevision\"2\n" +
	"\x16DeleteSnapshotResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\x81\x01\n" +
	"\x19GetReplicaMetadataRequest\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\tR\fsourceNodeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\tR\n" +
	"snapshotId\"\xf2\x01\n" +
	"\x1aGetReplicaMetadataResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12#\n" +
	"\rprocess_count\x18\x06 \x01(\x05R\fprocessCount\x12\x1f\n" +
	"\vprocess_ids\x18\a \x03(\tR\n" +
	"processIds\"\x94\x01\n" +
	"\x14FetchSnapshotRequest\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\tR\fsourceNodeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\tR\n" +
	"snapshotId\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\"\xd0\x01\n" +
	"\x15FetchSnapshotResponse\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\tR\fsourceNodeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\tR\n" +
	"snapshotId\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x1f\n" +
	"\vprocess_ids\x18\x05 \x03(\tR\n" +
	"processIds\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload2\xc0\x04\n" +
	"\x16PeerReplicationService\x12P\n" +
	"\vPutSnapshot\x12\x1f.procmesh.v1.PutSnapshotRequest\x1a .procmesh.v1.PutSnapshotResponse\x12b\n" +
	"\x11ReplicateSnapshot\x12%.procmesh.v1.ReplicateSnapshotRequest\x1a&.procmesh.v1.ReplicateSnapshotResponse\x12V\n" +
	"\rCheckSnapshot\x12!.procmesh.v1.CheckSnapshotRequest\x1a\".procmesh.v1.CheckSnapshotResponse\x12Y\n" +
	"\x0eDeleteSnapshot\x12\".procmesh.v1.DeleteSnapshotRequest\x1a#.procmesh.v1.DeleteSnapshotResponse\x12e\n" +
	"\x12GetReplicaMetadata\x12&.procmesh.v1.GetReplicaMetadataRequest\x1a'.procmesh.v1.GetReplicaMetadataResponse\x12V\n" +
	"\rFetchSnapshot\x12!.procmesh.v1.FetchSnapshotRequest\x1a\".procmesh.v1.FetchSnapshotResponseB;Z9github.com/qleelulu/procmesh/proto/procmesh/v1;procmeshv1b\x06proto3"

var (
	file_procmesh_v1_peer_replication_proto_rawDescOnce sync.Once
	file_procmesh_v1_peer_replication_proto_rawDescData []byte
)

func file_procmesh_v1_peer_replication_proto_rawDescGZIP() []byte {
	file_procmesh_v1_peer_replication_proto_rawDescOnce.Do(func() {
		file_procmesh_v1_peer_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_procmesh_v1_peer_replication_proto_rawDesc), len(file_procmesh_v1_peer_replication_proto_rawDesc)))
	})
	return file_procmesh_v1_peer_replication_proto_rawDescData
}

var file_procmesh_v1_peer_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_procmesh_v1_peer_replication_proto_goTypes = []any{
	(*PutSnapshotRequest)(nil),         // 0: procmesh.v1.PutSnapshotRequest
	(*PutSnapshotResponse)(nil),        // 1: procmesh.v1.PutSnapshotResponse
	(*ReplicateSnapshotRequest)(nil),   // 2: procmesh.v1.ReplicateSnapshotRequest
	(*ReplicateSnapshotResponse)(nil),  // 3: procmesh.v1.ReplicateSnapshotResponse
	(*CheckSnapshotRequest)(nil),       // 4: procmesh.v1.CheckSnapshotRequest
	(*CheckSnapshotResponse)(nil),      // 5: procmesh.v1.CheckSnapshotResponse
	(*DeleteSnapshotRequest)(nil),      // 6: procmesh.v1.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil),     // 7: procmesh.v1.DeleteSnapshotResponse
	(*GetReplicaMetadataRequest)(nil),  // 8: procmesh.v1.GetReplicaMetadataRequest
	(*GetReplicaMetadataResponse)(nil), // 9: procmesh.v1.GetReplicaMetadataResponse
	(*FetchSnapshotRequest)(nil),       // 10: procmesh.v1.FetchSnapshotRequest
	(*FetchSnapshotResponse)(nil),      // 11: procmesh.v1.FetchSnapshotResponse
}
var file_procmesh_v1_peer_replication_proto_depIdxs = []int32{
	0,  // 0: procmesh.v1.PeerReplicationService.PutSnapshot:input_type -> procmesh.v1.PutSnapshotRequest
	2,  // 1: procmesh.v1.PeerReplicationService.ReplicateSnapshot:input_type -> procmesh.v1.ReplicateSnapshotRequest
	4,  // 2: procmesh.v1.PeerReplicationService.CheckSnapshot:input_type -> procmesh.v1.CheckSnapshotRequest
	6,  // 3: procmesh.v1.PeerReplicationService.DeleteSnapshot:input_type -> procmesh.v1.DeleteSnapshotRequest
	8,  // 4: procmesh.v1.PeerReplicationService.GetReplicaMetadata:input_type -> procmesh.v1.GetReplicaMetadataRequest
	10, // 5: procmesh.v1.PeerReplicationService.FetchSnapshot:input_type -> procmesh.v1.FetchSnapshotRequest
	1,  // 6: procmesh.v1.PeerReplicationService.PutSnapshot:output_type -> procmesh.v1.PutSnapshotResponse
	3,  // 7: procmesh.v1.PeerReplicationService.ReplicateSnapshot:output_type -> procmesh.v1.ReplicateSnapshotResponse
	5,  // 8: procmesh.v1.PeerReplicationService.CheckSnapshot:output_type -> procmesh.v1.CheckSnapshotResponse
	7,  // 9: procmesh.v1.PeerReplicationService.DeleteSnapshot:output_type -> procmesh.v1.DeleteSnapshotResponse
	9,  // 10: procmesh.v1.PeerReplicationService.GetReplicaMetadata:output_type -> procmesh.v1.GetReplicaMetadataResponse
	11, // 11: procmesh.v1.PeerReplicationService.FetchSnapshot:output_type -> procmesh.v1.FetchSnapshotResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_procmesh_v1_peer_replication_proto_init() }
func file_procmesh_v1_peer_replication_proto_init() {
	if File_procmesh_v1_peer_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_procmesh_v1_peer_replication_proto_rawDesc), len(file_procmesh_v1_peer_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_procmesh_v1_peer_replication_proto_goTypes,
		DependencyIndexes: file_procmesh_v1_peer_replication_proto_depIdxs,
		MessageInfos:      file_procmesh_v1_peer_replication_proto_msgTypes,
	}.Build()
	File_procmesh_v1_peer_replication_proto = out.File
	file_procmesh_v1_peer_replication_proto_goTypes = nil
	file_procmesh_v1_peer_replication_proto_depIdxs = nil
}
