// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: procmesh/v1/process_types.proto

package procmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Backoff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialMs     int64                  `protobuf:"varint,1,opt,name=initial_ms,json=initialMs,proto3" json:"initial_ms,omitempty"`
	MaxMs         int64                  `protobuf:"varint,2,opt,name=max_ms,json=maxMs,proto3" json:"max_ms,omitempty"`
	Multiplier    float64                `protobuf:"fixed64,3,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backoff) Reset() {
	*x = Backoff{}
	mi := &file_procmesh_v1_process_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backoff) ProtoMessage() {}

func (x *Backoff) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_process_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backoff.ProtoReflect.Descriptor instead.
func (*Backoff) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_process_types_proto_rawDescGZIP(), []int{0}
}

func (x *Backoff) GetInitialMs() int64 {
	if x != nil {
		return x.InitialMs
	}
	return 0
}

func (x *Backoff) GetMaxMs() int64 {
	if x != nil {
		return x.MaxMs
	}
	return 0
}

func (x *Backoff) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

type RestartPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"` // never | always | on-failure
	MaxRetries    int32                  `protobuf:"varint,2,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	RetryWindowMs int64                  `protobuf:"varint,3,opt,name=retry_window_ms,json=retryWindowMs,proto3" json:"retry_window_ms,omitempty"`
	Backoff       *Backoff               `protobuf:"bytes,4,opt,name=backoff,proto3" json:"backoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartPolicy) Reset() {
	*x = RestartPolicy{}
	mi := &file_procmesh_v1_process_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartPolicy) ProtoMessage() {}

func (x *RestartPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_process_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartPolicy.ProtoReflect.Descriptor instead.
func (*RestartPolicy) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_process_types_proto_rawDescGZIP(), []int{1}
}

func (x *RestartPolicy) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RestartPolicy) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *RestartPolicy) GetRetryWindowMs() int64 {
	if x != nil {
		return x.RetryWindowMs
	}
	return 0
}

func (x *RestartPolicy) GetBackoff() *Backoff {
	if x != nil {
		return x.Backoff
	}
	return nil
}

type HealthCheck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // alive | http | tcp | exec
	Url               string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method            string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Address           string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Command           string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	ExpectedStatus    int32                  `protobuf:"varint,6,opt,name=expected_status,json=expectedStatus,proto3" json:"expected_status,omitempty"`
	Args              []string               `protobuf:"bytes,7,rep,name=args,proto3" json:"args,omitempty"`
	InitialDelayMs    int64                  `protobuf:"varint,8,opt,name=initial_delay_ms,json=initialDelayMs,proto3" json:"initial_delay_ms,omitempty"`
	IntervalMs        int64                  `protobuf:"varint,9,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	TimeoutMs         int64                  `protobuf:"varint,10,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	FailureThreshold  int32                  `protobuf:"varint,11,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	SuccessThreshold  int32                  `protobuf:"varint,12,opt,name=success_threshold,json=successThreshold,proto3" json:"success_threshold,omitempty"`
	RestartOnFailure  bool                   `protobuf:"varint,13,opt,name=restart_on_failure,json=restartOnFailure,proto3" json:"restart_on_failure,omitempty"`
	RestartCooldownMs int64                  `protobuf:"varint,14,opt,name=restart_cooldown_ms,json=restartCooldownMs,proto3" json:"restart_cooldown_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_procmesh_v1_process_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_process_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_process_types_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheck) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HealthCheck) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HealthCheck) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HealthCheck) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HealthCheck) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *HealthCheck) GetExpectedStatus() int32 {
	if x != nil {
		return x.ExpectedStatus
	}
	return 0
}

func (x *HealthCheck) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *HealthCheck) GetInitialDelayMs() int64 {
	if x != nil {
		return x.InitialDelayMs
	}
	return 0
}

func (x *HealthCheck) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *HealthCheck) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *HealthCheck) GetFailureThreshold() int32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *HealthCheck) GetSuccessThreshold() int32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

func (x *HealthCheck) GetRestartOnFailure() bool {
	if x != nil {
		return x.RestartOnFailure
	}
	return false
}

func (x *HealthCheck) GetRestartCooldownMs() int64 {
	if x != nil {
		return x.RestartCooldownMs
	}
	return 0
}

type LogPolicy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxSize        int64                  `protobuf:"varint,1,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	MaxFiles       int32                  `protobuf:"varint,2,opt,name=max_files,json=maxFiles,proto3" json:"max_files,omitempty"`
	MaxAgeSeconds  int64                  `protobuf:"varint,3,opt,name=max_age_seconds,json=maxAgeSeconds,proto3" json:"max_age_seconds,omitempty"`
	Compress       bool                   `protobuf:"varint,4,opt,name=compress,proto3" json:"compress,omitempty"`
	Directory      string                 `protobuf:"bytes,5,opt,name=directory,proto3" json:"directory,omitempty"`
	RedirectStderr bool                   `protobuf:"varint,6,opt,name=redirect_stderr,json=redirectStderr,proto3" json:"redirect_stderr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogPolicy) Reset() {
	*x = LogPolicy{}
	mi := &file_procmesh_v1_process_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogPolicy) ProtoMessage() {}

func (x *LogPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_process_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogPolicy.ProtoReflect.Descriptor instead.
func (*LogPolicy) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_process_types_proto_rawDescGZIP(), []int{3}
}

func (x *LogPolicy) GetMaxSize() int64 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *LogPolicy) GetMaxFiles() int32 {
	if x != nil {
		return x.MaxFiles
	}
	return 0
}

func (x *LogPolicy) GetMaxAgeSeconds() int64 {
	if x != nil {
		return x.MaxAgeSeconds
	}
	return 0
}

func (x *LogPolicy) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

func (x *LogPolicy) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *LogPolicy) GetRedirectStderr() bool {
	if x != nil {
		return x.RedirectStderr
	}
	return false
}

type ResourceLimit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuQuotaMillis int64                  `protobuf:"varint,1,opt,name=cpu_quota_millis,json=cpuQuotaMillis,proto3" json:"cpu_quota_millis,omitempty"`
	MemoryBytes    int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	OpenFiles      int64                  `protobuf:"varint,3,opt,name=open_files,json=openFiles,proto3" json:"open_files,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceLimit) Reset() {
	*x = ResourceLimit{}
	mi := &file_procmesh_v1_process_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimit) ProtoMessage() {}

func (x *ResourceLimit) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_process_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimit.ProtoReflect.Descriptor instead.
func (*ResourceLimit) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_process_types_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceLimit) GetCpuQuotaMillis() int64 {
	if x != nil {
		return x.CpuQuotaMillis
	}
	return 0
}

func (x *ResourceLimit) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceLimit) GetOpenFiles() int64 {
	if x != nil {
		return x.OpenFiles
	}
	return 0
}

type Dependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessName   string                 `protobuf:"bytes,1,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	Condition     string                 `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"` // STARTED | HEALTHY
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_procmesh_v1_process_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_process_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_process_types_proto_rawDescGZIP(), []int{5}
}

func (x *Dependency) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *Dependency) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type ProcessSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProcessId        string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerAgentId     string                 `protobuf:"bytes,3,opt,name=owner_agent_id,json=ownerAgentId,proto3" json:"owner_agent_id,omitempty"`
	Group            string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Command          string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	Args             []string               `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	WorkingDirectory string                 `protobuf:"bytes,7,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	RunAsUser        string                 `protobuf:"bytes,8,opt,name=run_as_user,json=runAsUser,proto3" json:"run_as_user,omitempty"`
	Environment      map[string]string      `protobuf:"bytes,9,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Instances        int32                  `protobuf:"varint,10,opt,name=instances,proto3" json:"instances,omitempty"`
	Autostart        bool                   `protobuf:"varint,11,opt,name=autostart,proto3" json:"autostart,omitempty"`
	StopSignal       string                 `protobuf:"bytes,12,opt,name=stop_signal,json=stopSignal,proto3" json:"stop_signal,omitempty"`
	KillSignal       string                 `protobuf:"bytes,13,opt,name=kill_signal,json=killSignal,proto3" json:"kill_signal,omitempty"`
	StopTimeoutMs    int64                  `protobuf:"varint,14,opt,name=stop_timeout_ms,json=stopTimeoutMs,proto3" json:"stop_timeout_ms,omitempty"`
	StartupPriority  int32                  `protobuf:"varint,15,opt,name=startup_priority,json=startupPriority,proto3" json:"startup_priority,omitempty"`
	Restart          *RestartPolicy         `protobuf:"bytes,16,opt,name=restart,proto3" json:"restart,omitempty"`
	Health           *HealthCheck           `protobuf:"bytes,17,opt,name=health,proto3" json:"health,omitempty"`
	Log              *LogPolicy             `protobuf:"bytes,18,opt,name=log,proto3" json:"log,omitempty"`
	Resources        *ResourceLimit         `protobuf:"bytes,19,opt,name=resources,proto3" json:"resources,omitempty"`
	Dependencies     []*Dependency          `protobuf:"bytes,20,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	LatestRevision   int64                  `protobuf:"varint,21,opt,name=latest_revision,json=latestRevision,proto3" json:"latest_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessSpec) Reset() {
	*x = ProcessSpec{}
	mi := &file_procmesh_v1_process_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSpec) ProtoMessage() {}

func (x *ProcessSpec) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_process_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSpec.ProtoReflect.Descriptor instead.
func (*ProcessSpec) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_process_types_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessSpec) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ProcessSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessSpec) GetOwnerAgentId() string {
	if x != nil {
		return x.OwnerAgentId
	}
	return ""
}

func (x *ProcessSpec) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ProcessSpec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ProcessSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProcessSpec) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *ProcessSpec) GetRunAsUser() string {
	if x != nil {
		return x.RunAsUser
	}
	return ""
}

func (x *ProcessSpec) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ProcessSpec) GetInstances() int32 {
	if x != nil {
		return x.Instances
	}
	return 0
}

func (x *ProcessSpec) GetAutostart() bool {
	if x != nil {
		return x.Autostart
	}
	return false
}

func (x *ProcessSpec) GetStopSignal() string {
	if x != nil {
		return x.StopSignal
	}
	return ""
}

func (x *ProcessSpec) GetKillSignal() string {
	if x != nil {
		return x.KillSignal
	}
	return ""
}

func (x *ProcessSpec) GetStopTimeoutMs() int64 {
	if x != nil {
		return x.StopTimeoutMs
	}
	return 0
}

func (x *ProcessSpec) GetStartupPriority() int32 {
	if x != nil {
		return x.StartupPriority
	}
	return 0
}

func (x *ProcessSpec) GetRestart() *RestartPolicy {
	if x != nil {
		return x.Restart
	}
	return nil
}

func (x *ProcessSpec) GetHealth() *HealthCheck {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *ProcessSpec) GetLog() *LogPolicy {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *ProcessSpec) GetResources() *ResourceLimit {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ProcessSpec) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ProcessSpec) GetLatestRevision() int64 {
	if x != nil {
		return x.LatestRevision
	}
	return 0
}

type Instance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Ordinal        int32                  `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Desired        string                 `protobuf:"bytes,3,opt,name=desired,proto3" json:"desired,omitempty"`
	Observed       string                 `protobuf:"bytes,4,opt,name=observed,proto3" json:"observed,omitempty"`
	Health         string                 `protobuf:"bytes,5,opt,name=health,proto3" json:"health,omitempty"`
	Pid            int32                  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	ActiveRevision int64                  `protobuf:"varint,7,opt,name=active_revision,json=activeRevision,proto3" json:"active_revision,omitempty"`
	RestartCount   int32                  `protobuf:"varint,8,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	ExitCode       int32                  `protobuf:"varint,9,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	HasExitCode    bool                   `protobuf:"varint,10,opt,name=has_exit_code,json=hasExitCode,proto3" json:"has_exit_code,omitempty"`
	StartedUnixMs  int64                  `protobuf:"varint,11,opt,name=started_unix_ms,json=startedUnixMs,proto3" json:"started_unix_ms,omitempty"`
	LogPathPending bool                   `protobuf:"varint,12,opt,name=log_path_pending,json=logPathPending,proto3" json:"log_path_pending,omitempty"`
	LastError      string                 `protobuf:"bytes,13,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_procmesh_v1_process_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_process_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_process_types_proto_rawDescGZIP(), []int{7}
}

func (x *Instance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Instance) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *Instance) GetDesired() string {
	if x != nil {
		return x.Desired
	}
	return ""
}

func (x *Instance) GetObserved() string {
	if x != nil {
		return x.Observed
	}
	return ""
}

func (x *Instance) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *Instance) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Instance) GetActiveRevision() int64 {
	if x != nil {
		return x.ActiveRevision
	}
	return 0
}

func (x *Instance) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *Instance) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Instance) GetHasExitCode() bool {
	if x != nil {
		return x.HasExitCode
	}
	return false
}

func (x *Instance) GetStartedUnixMs() int64 {
	if x != nil {
		return x.StartedUnixMs
	}
	return 0
}

func (x *Instance) GetLogPathPending() bool {
	if x != nil {
		return x.LogPathPending
	}
	return false
}

func (x *Instance) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ProcessView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Spec          *ProcessSpec           `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Instances     []*Instance            `protobuf:"bytes,3,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessView) Reset() {
	*x = ProcessView{}
	mi := &file_procmesh_v1_process_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessView) ProtoMessage() {}

func (x *ProcessView) ProtoReflect() protoreflect.Message {
	mi := &file_procmesh_v1_process_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessView.ProtoReflect.Descriptor instead.
func (*ProcessView) Descriptor() ([]byte, []int) {
	return file_procmesh_v1_process_types_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessView) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ProcessView) GetSpec() *ProcessSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ProcessView) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

var File_procmesh_v1_process_types_proto protoreflect.FileDescriptor

const file_procmesh_v1_process_types_proto_rawDesc = "" +
	"\n" +
	"\x1fprocmesh/v1/process_types.proto\x12\vprocmesh.v1\"_\n" +
	"\aBackoff\x12\x1d\n" +
	"\n" +
	"initial_ms\x18\x01 \x01(\x03R\tinitialMs\x12\x15\n" +
	"\x06max_ms\x18\x02 \x01(\x03R\x05maxMs\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x03 \x01(\x01R\n" +
	"multiplier\"\x9c\x01\n" +
	"\rRestartPolicy\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1f\n" +
	"\vmax_retries\x18\x02 \x01(\x05R\n" +
	"maxRetries\x12&\n" +
	"\x0fretry_window_ms\x18\x03 \x01(\x03R\rretryWindowMs\x12.\n" +
	"\abackoff\x18\x04 \x01(\v2\x14.procmesh.v1.BackoffR\abackoff\"\xde\x03\n" +
	"\vHealthCheck\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12'\n" +
	"\x0fexpected_status\x18\x06 \x01(\x05R\x0eexpectedStatus\x12\x12\n" +
	"\x04args\x18\a \x03(\tR\x04args\x12(\n" +
	"\x10initial_delay_ms\x18\b \x01(\x03R\x0einitialDelayMs\x12\x1f\n" +
	"\vinterval_ms\x18\t \x01(\x03R\n" +
	"intervalMs\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\n" +
	" \x01(\x03R\ttimeoutMs\x12+\n" +
	"\x11failure_threshold\x18\v \x01(\x05R\x10failureThreshold\x12+\n" +
	"\x11success_threshold\x18\f \x01(\x05R\x10successThreshold\x12,\n" +
	"\x12restart_on_failure\x18\r \x01(\bR\x10restartOnFailure\x12.\n" +
	"\x13restart_cooldown_ms\x18\x0e \x01(\x03R\x11restartCooldownMs\"\xce\x01\n" +
	"\tLogPolicy\x12\x19\n" +
	"\bmax_size\x18\x01 \x01(\x03R\amaxSize\x12\x1b\n" +
	"\tmax_files\x18\x02 \x01(\x05R\bmaxFiles\x12&\n" +
	"\x0fmax_age_seconds\x18\x03 \x01(\x03R\rmaxAgeSeconds\x12\x1a\n" +
	"\bcompress\x18\x04 \x01(\bR\bcompress\x12\x1c\n" +
	"\tdirectory\x18\x05 \x01(\tR\tdirectory\x12'\n" +
	"\x0fredirect_stderr\x18\x06 \x01(\bR\x0eredirectStderr\"{\n" +
	"\rResourceLimit\x12(\n" +
	"\x10cpu_quota_millis\x18\x01 \x01(\x03R\x0ecpuQuotaMillis\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"open_files\x18\x03 \x01(\x03R\topenFiles\"M\n" +
	"\n" +
	"Dependency\x12!\n" +
	"\fprocess_name\x18\x01 \x01(\tR\vprocessName\x12\x1c\n" +
	"\tcondition\x18\x02 \x01(\tR\tcondition\"\x87\a\n" +
	"\vProcessSpec\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x0eowner_agent_id\x18\x03 \x01(\tR\fownerAgentId\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x06 \x03(\tR\x04args\x12+\n" +
	"\x11working_directory\x18\a \x01(\tR\x10workingDirectory\x12\x1e\n" +
	"\vrun_as_user\x18\b \x01(\tR\trunAsUser\x12K\n" +
	"\venvironment\x18\t \x03(\v2).procmesh.v1.ProcessSpec.EnvironmentEntryR\venvironment\x12\x1c\n" +
	"\tinstances\x18\n" +
	" \x01(\x05R\tinstances\x12\x1c\n" +
	"\tautostart\x18\v \x01(\bR\tautostart\x12\x1f\n" +
	"\vstop_signal\x18\f \x01(\tR\n" +
	"stopSignal\x12\x1f\n" +
	"\vkill_signal\x18\r \x01(\tR\n" +
	"killSignal\x12&\n" +
	"\x0fstop_timeout_ms\x18\x0e \x01(\x03R\rstopTimeoutMs\x12)\n" +
	"\x10startup_priority\x18\x0f \x01(\x05R\x0fstartupPriority\x124\n" +
	"\arestart\x18\x10 \x01(\v2\x1a.procmesh.v1.RestartPolicyR\arestart\x120\n" +
	"\x06health\x18\x11 \x01(\v2\x18.procmesh.v1.HealthCheckR\x06health\x12(\n" +
	"\x03log\x18\x12 \x01(\v2\x16.procmesh.v1.LogPolicyR\x03log\x128\n" +
	"\tresources\x18\x13 \x01(\v2\x1a.procmesh.v1.ResourceLimitR\tresources\x12;\n" +
	"\fdependencies\x18\x14 \x03(\v2\x17.procmesh.v1.DependencyR\fdependencies\x12'\n" +
	"\x0flatest_revision\x18\x15 \x01(\x03R\x0elatestRevision\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x03\n" +
	"\bInstance\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\x05R\aordinal\x12\x18\n" +
	"\adesired\x18\x03 \x01(\tR\adesired\x12\x1a\n" +
	"\bobserved\x18\x04 \x01(\tR\bobserved\x12\x16\n" +
	"\x06health\x18\x05 \x01(\tR\x06health\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x05R\x03pid\x12'\n" +
	"\x0factive_revision\x18\a \x01(\x03R\x0eactiveRevision\x12#\n" +
	"\rrestart_count\x18\b \x01(\x05R\frestartCount\x12\x1b\n" +
	"\texit_code\x18\t \x01(\x05R\bexitCode\x12\"\n" +
	"\rhas_exit_code\x18\n" +
	" \x01(\bR\vhasExitCode\x12&\n" +
	"\x0fstarted_unix_ms\x18\v \x01(\x03R\rstartedUnixMs\x12(\n" +
	"\x10log_path_pending\x18\f \x01(\bR\x0elogPathPending\x12\x1d\n" +
	"\n" +
	"last_error\x18\r \x01(\tR\tlastError\"\x8f\x01\n" +
	"\vProcessView\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12,\n" +
	"\x04spec\x18\x02 \x01(\v2\x18.procmesh.v1.ProcessSpecR\x04spec\x123\n" +
	"\tinstances\x18\x03 \x03(\v2\x15.procmesh.v1.InstanceR\tinstancesB;Z9github.com/qleelulu/procmesh/proto/procmesh/v1;procmeshv1b\x06proto3"

var (
	file_procmesh_v1_process_types_proto_rawDescOnce sync.Once
	file_procmesh_v1_process_types_proto_rawDescData []byte
)

func file_procmesh_v1_process_types_proto_rawDescGZIP() []byte {
	file_procmesh_v1_process_types_proto_rawDescOnce.Do(func() {
		file_procmesh_v1_process_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_procmesh_v1_process_types_proto_rawDesc), len(file_procmesh_v1_process_types_proto_rawDesc)))
	})
	return file_procmesh_v1_process_types_proto_rawDescData
}

var file_procmesh_v1_process_types_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_procmesh_v1_process_types_proto_goTypes = []any{
	(*Backoff)(nil),       // 0: procmesh.v1.Backoff
	(*RestartPolicy)(nil), // 1: procmesh.v1.RestartPolicy
	(*HealthCheck)(nil),   // 2: procmesh.v1.HealthCheck
	(*LogPolicy)(nil),     // 3: procmesh.v1.LogPolicy
	(*ResourceLimit)(nil), // 4: procmesh.v1.ResourceLimit
	(*Dependency)(nil),    // 5: procmesh.v1.Dependency
	(*ProcessSpec)(nil),   // 6: procmesh.v1.ProcessSpec
	(*Instance)(nil),      // 7: procmesh.v1.Instance
	(*ProcessView)(nil),   // 8: procmesh.v1.ProcessView
	nil,                   // 9: procmesh.v1.ProcessSpec.EnvironmentEntry
}
var file_procmesh_v1_process_types_proto_depIdxs = []int32{
	0, // 0: procmesh.v1.RestartPolicy.backoff:type_name -> procmesh.v1.Backoff
	9, // 1: procmesh.v1.ProcessSpec.environment:type_name -> procmesh.v1.ProcessSpec.EnvironmentEntry
	1, // 2: procmesh.v1.ProcessSpec.restart:type_name -> procmesh.v1.RestartPolicy
	2, // 3: procmesh.v1.ProcessSpec.health:type_name -> procmesh.v1.HealthCheck
	3, // 4: procmesh.v1.ProcessSpec.log:type_name -> procmesh.v1.LogPolicy
	4, // 5: procmesh.v1.ProcessSpec.resources:type_name -> procmesh.v1.ResourceLimit
	5, // 6: procmesh.v1.ProcessSpec.dependencies:type_name -> procmesh.v1.Dependency
	6, // 7: procmesh.v1.ProcessView.spec:type_name -> procmesh.v1.ProcessSpec
	7, // 8: procmesh.v1.ProcessView.instances:type_name -> procmesh.v1.Instance
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_procmesh_v1_process_types_proto_init() }
func file_procmesh_v1_process_types_proto_init() {
	if File_procmesh_v1_process_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_procmesh_v1_process_types_proto_rawDesc), len(file_procmesh_v1_process_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_procmesh_v1_process_types_proto_goTypes,
		DependencyIndexes: file_procmesh_v1_process_types_proto_depIdxs,
		MessageInfos:      file_procmesh_v1_process_types_proto_msgTypes,
	}.Build()
	File_procmesh_v1_process_types_proto = out.File
	file_procmesh_v1_process_types_proto_goTypes = nil
	file_procmesh_v1_process_types_proto_depIdxs = nil
}
