// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/shim/v1/shim.proto

package shimpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd           string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	RunAsUser     string                 `protobuf:"bytes,5,opt,name=run_as_user,json=runAsUser,proto3" json:"run_as_user,omitempty"`
	StdoutPath    string                 `protobuf:"bytes,6,opt,name=stdout_path,json=stdoutPath,proto3" json:"stdout_path,omitempty"`
	StderrPath    string                 `protobuf:"bytes,7,opt,name=stderr_path,json=stderrPath,proto3" json:"stderr_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_proto_shim_v1_shim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shim_v1_shim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_proto_shim_v1_shim_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *StartRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StartRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *StartRequest) GetRunAsUser() string {
	if x != nil {
		return x.RunAsUser
	}
	return ""
}

func (x *StartRequest) GetStdoutPath() string {
	if x != nil {
		return x.StdoutPath
	}
	return ""
}

func (x *StartRequest) GetStderrPath() string {
	if x != nil {
		return x.StderrPath
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_proto_shim_v1_shim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shim_v1_shim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_proto_shim_v1_shim_proto_rawDescGZIP(), []int{1}
}

func (x *StartResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        string                 `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	KillSignal    string                 `protobuf:"bytes,3,opt,name=kill_signal,json=killSignal,proto3" json:"kill_signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_shim_v1_shim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shim_v1_shim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_shim_v1_shim_proto_rawDescGZIP(), []int{2}
}

func (x *StopRequest) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *StopRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *StopRequest) GetKillSignal() string {
	if x != nil {
		return x.KillSignal
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_shim_v1_shim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shim_v1_shim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_shim_v1_shim_proto_rawDescGZIP(), []int{3}
}

func (x *StopResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StopResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        string                 `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_proto_shim_v1_shim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shim_v1_shim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_proto_shim_v1_shim_proto_rawDescGZIP(), []int{4}
}

func (x *SignalRequest) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_proto_shim_v1_shim_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shim_v1_shim_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_proto_shim_v1_shim_proto_rawDescGZIP(), []int{5}
}

func (x *SignalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_shim_v1_shim_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shim_v1_shim_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_shim_v1_shim_proto_rawDescGZIP(), []int{6}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Alive         bool                   `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	StartedUnix   int64                  `protobuf:"varint,4,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_shim_v1_shim_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shim_v1_shim_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_shim_v1_shim_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StatusResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *StatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StatusResponse) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

func (x *StatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WaitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitRequest) Reset() {
	*x = WaitRequest{}
	mi := &file_proto_shim_v1_shim_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitRequest) ProtoMessage() {}

func (x *WaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shim_v1_shim_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitRequest.ProtoReflect.Descriptor instead.
func (*WaitRequest) Descriptor() ([]byte, []int) {
	return file_proto_shim_v1_shim_proto_rawDescGZIP(), []int{8}
}

type WaitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitResponse) Reset() {
	*x = WaitResponse{}
	mi := &file_proto_shim_v1_shim_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitResponse) ProtoMessage() {}

func (x *WaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shim_v1_shim_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitResponse.ProtoReflect.Descriptor instead.
func (*WaitResponse) Descriptor() ([]byte, []int) {
	return file_proto_shim_v1_shim_proto_rawDescGZIP(), []int{9}
}

func (x *WaitResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *WaitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Start
	//	*Envelope_Stop
	//	*Envelope_Signal
	//	*Envelope_Status
	//	*Envelope_Wait
	//	*Envelope_StartOk
	//	*Envelope_StopOk
	//	*Envelope_SignalOk
	//	*Envelope_StatusOk
	//	*Envelope_WaitOk
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_shim_v1_shim_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shim_v1_shim_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_shim_v1_shim_proto_rawDescGZIP(), []int{10}
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetStart() *StartRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *Envelope) GetStop() *StopRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *Envelope) GetSignal() *SignalRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *Envelope) GetStatus() *StatusRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *Envelope) GetWait() *WaitRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Wait); ok {
			return x.Wait
		}
	}
	return nil
}

func (x *Envelope) GetStartOk() *StartResponse {
	if x != nil {
		if x, ok := x.Body.(*Envelope_StartOk); ok {
			return x.StartOk
		}
	}
	return nil
}

func (x *Envelope) GetStopOk() *StopResponse {
	if x != nil {
		if x, ok := x.Body.(*Envelope_StopOk); ok {
			return x.StopOk
		}
	}
	return nil
}

func (x *Envelope) GetSignalOk() *SignalResponse {
	if x != nil {
		if x, ok := x.Body.(*Envelope_SignalOk); ok {
			return x.SignalOk
		}
	}
	return nil
}

func (x *Envelope) GetStatusOk() *StatusResponse {
	if x != nil {
		if x, ok := x.Body.(*Envelope_StatusOk); ok {
			return x.StatusOk
		}
	}
	return nil
}

func (x *Envelope) GetWaitOk() *WaitResponse {
	if x != nil {
		if x, ok := x.Body.(*Envelope_WaitOk); ok {
			return x.WaitOk
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Start struct {
	Start *StartRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type Envelope_Stop struct {
	Stop *StopRequest `protobuf:"bytes,2,opt,name=stop,proto3,oneof"`
}

type Envelope_Signal struct {
	Signal *SignalRequest `protobuf:"bytes,3,opt,name=signal,proto3,oneof"`
}

type Envelope_Status struct {
	Status *StatusRequest `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

type Envelope_Wait struct {
	Wait *WaitRequest `protobuf:"bytes,5,opt,name=wait,proto3,oneof"`
}

type Envelope_StartOk struct {
	StartOk *StartResponse `protobuf:"bytes,10,opt,name=start_ok,json=startOk,proto3,oneof"`
}

type Envelope_StopOk struct {
	StopOk *StopResponse `protobuf:"bytes,11,opt,name=stop_ok,json=stopOk,proto3,oneof"`
}

type Envelope_SignalOk struct {
	SignalOk *SignalResponse `protobuf:"bytes,12,opt,name=signal_ok,json=signalOk,proto3,oneof"`
}

type Envelope_StatusOk struct {
	StatusOk *StatusResponse `protobuf:"bytes,13,opt,name=status_ok,json=statusOk,proto3,oneof"`
}

type Envelope_WaitOk struct {
	WaitOk *WaitResponse `protobuf:"bytes,14,opt,name=wait_ok,json=waitOk,proto3,oneof"`
}

func (*Envelope_Start) isEnvelope_Body() {}

func (*Envelope_Stop) isEnvelope_Body() {}

func (*Envelope_Signal) isEnvelope_Body() {}

func (*Envelope_Status) isEnvelope_Body() {}

func (*Envelope_Wait) isEnvelope_Body() {}

func (*Envelope_StartOk) isEnvelope_Body() {}

func (*Envelope_StopOk) isEnvelope_Body() {}

func (*Envelope_SignalOk) isEnvelope_Body() {}

func (*Envelope_StatusOk) isEnvelope_Body() {}

func (*Envelope_WaitOk) isEnvelope_Body() {}

var File_proto_shim_v1_shim_proto protoreflect.FileDescriptor

const file_proto_shim_v1_shim_proto_rawDesc = "" +
	"\n" +
	"\x18proto/shim/v1/shim.proto\x12\x10procmesh.shim.v1\"\xa3\x02\n" +
	"\fStartRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x129\n" +
	"\x03env\x18\x03 \x03(\v2'.procmesh.shim.v1.StartRequest.EnvEntryR\x03env\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12\x1e\n" +
	"\vrun_as_user\x18\x05 \x01(\tR\trunAsUser\x12\x1f\n" +
	"\vstdout_path\x18\x06 \x01(\tR\n" +
	"stdoutPath\x12\x1f\n" +
	"\vstderr_path\x18\a \x01(\tR\n" +
	"stderrPath\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\rStartResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"e\n" +
	"\vStopRequest\x12\x16\n" +
	"\x06signal\x18\x01 \x01(\tR\x06signal\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x05R\ttimeoutMs\x12\x1f\n" +
	"\vkill_signal\x18\x03 \x01(\tR\n" +
	"killSignal\"A\n" +
	"\fStopResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"'\n" +
	"\rSignalRequest\x12\x16\n" +
	"\x06signal\x18\x01 \x01(\tR\x06signal\"&\n" +
	"\x0eSignalResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x0f\n" +
	"\rStatusRequest\"\x8e\x01\n" +
	"\x0eStatusResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x14\n" +
	"\x05alive\x18\x02 \x01(\bR\x05alive\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12!\n" +
	"\fstarted_unix\x18\x04 \x01(\x03R\vstartedUnix\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\r\n" +
	"\vWaitRequest\"A\n" +
	"\fWaitResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xe0\x04\n" +
	"\bEnvelope\x126\n" +
	"\x05start\x18\x01 \x01(\v2\x1e.procmesh.shim.v1.StartRequestH\x00R\x05start\x123\n" +
	"\x04stop\x18\x02 \x01(\v2\x1d.procmesh.shim.v1.StopRequestH\x00R\x04stop\x129\n" +
	"\x06signal\x18\x03 \x01(\v2\x1f.procmesh.shim.v1.SignalRequestH\x00R\x06signal\x129\n" +
	"\x06status\x18\x04 \x01(\v2\x1f.procmesh.shim.v1.StatusRequestH\x00R\x06status\x123\n" +
	"\x04wait\x18\x05 \x01(\v2\x1d.procmesh.shim.v1.WaitRequestH\x00R\x04wait\x12<\n" +
	"\bstart_ok\x18\n" +
	" \x01(\v2\x1f.procmesh.shim.v1.StartResponseH\x00R\astartOk\x129\n" +
	"\astop_ok\x18\v \x01(\v2\x1e.procmesh.shim.v1.StopResponseH\x00R\x06stopOk\x12?\n" +
	"\tsignal_ok\x18\f \x01(\v2 .procmesh.shim.v1.SignalResponseH\x00R\bsignalOk\x12?\n" +
	"\tstatus_ok\x18\r \x01(\v2 .procmesh.shim.v1.StatusResponseH\x00R\bstatusOk\x129\n" +
	"\await_ok\x18\x0e \x01(\v2\x1e.procmesh.shim.v1.WaitResponseH\x00R\x06waitOkB\x06\n" +
	"\x04bodyB3Z1github.com/qleelulu/procmesh/proto/shim/v1;shimpbb\x06proto3"

var (
	file_proto_shim_v1_shim_proto_rawDescOnce sync.Once
	file_proto_shim_v1_shim_proto_rawDescData []byte
)

func file_proto_shim_v1_shim_proto_rawDescGZIP() []byte {
	file_proto_shim_v1_shim_proto_rawDescOnce.Do(func() {
		file_proto_shim_v1_shim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shim_v1_shim_proto_rawDesc), len(file_proto_shim_v1_shim_proto_rawDesc)))
	})
	return file_proto_shim_v1_shim_proto_rawDescData
}

var file_proto_shim_v1_shim_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_shim_v1_shim_proto_goTypes = []any{
	(*StartRequest)(nil),   // 0: procmesh.shim.v1.StartRequest
	(*StartResponse)(nil),  // 1: procmesh.shim.v1.StartResponse
	(*StopRequest)(nil),    // 2: procmesh.shim.v1.StopRequest
	(*StopResponse)(nil),   // 3: procmesh.shim.v1.StopResponse
	(*SignalRequest)(nil),  // 4: procmesh.shim.v1.SignalRequest
	(*SignalResponse)(nil), // 5: procmesh.shim.v1.SignalResponse
	(*StatusRequest)(nil),  // 6: procmesh.shim.v1.StatusRequest
	(*StatusResponse)(nil), // 7: procmesh.shim.v1.StatusResponse
	(*WaitRequest)(nil),    // 8: procmesh.shim.v1.WaitRequest
	(*WaitResponse)(nil),   // 9: procmesh.shim.v1.WaitResponse
	(*Envelope)(nil),       // 10: procmesh.shim.v1.Envelope
	nil,                    // 11: procmesh.shim.v1.StartRequest.EnvEntry
}
var file_proto_shim_v1_shim_proto_depIdxs = []int32{
	11, // 0: procmesh.shim.v1.StartRequest.env:type_name -> procmesh.shim.v1.StartRequest.EnvEntry
	0,  // 1: procmesh.shim.v1.Envelope.start:type_name -> procmesh.shim.v1.StartRequest
	2,  // 2: procmesh.shim.v1.Envelope.stop:type_name -> procmesh.shim.v1.StopRequest
	4,  // 3: procmesh.shim.v1.Envelope.signal:type_name -> procmesh.shim.v1.SignalRequest
	6,  // 4: procmesh.shim.v1.Envelope.status:type_name -> procmesh.shim.v1.StatusRequest
	8,  // 5: procmesh.shim.v1.Envelope.wait:type_name -> procmesh.shim.v1.WaitRequest
	1,  // 6: procmesh.shim.v1.Envelope.start_ok:type_name -> procmesh.shim.v1.StartResponse
	3,  // 7: procmesh.shim.v1.Envelope.stop_ok:type_name -> procmesh.shim.v1.StopResponse
	5,  // 8: procmesh.shim.v1.Envelope.signal_ok:type_name -> procmesh.shim.v1.SignalResponse
	7,  // 9: procmesh.shim.v1.Envelope.status_ok:type_name -> procmesh.shim.v1.StatusResponse
	9,  // 10: procmesh.shim.v1.Envelope.wait_ok:type_name -> procmesh.shim.v1.WaitResponse
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_shim_v1_shim_proto_init() }
func file_proto_shim_v1_shim_proto_init() {
	if File_proto_shim_v1_shim_proto != nil {
		return
	}
	file_proto_shim_v1_shim_proto_msgTypes[10].OneofWrappers = []any{
		(*Envelope_Start)(nil),
		(*Envelope_Stop)(nil),
		(*Envelope_Signal)(nil),
		(*Envelope_Status)(nil),
		(*Envelope_Wait)(nil),
		(*Envelope_StartOk)(nil),
		(*Envelope_StopOk)(nil),
		(*Envelope_SignalOk)(nil),
		(*Envelope_StatusOk)(nil),
		(*Envelope_WaitOk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shim_v1_shim_proto_rawDesc), len(file_proto_shim_v1_shim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_shim_v1_shim_proto_goTypes,
		DependencyIndexes: file_proto_shim_v1_shim_proto_depIdxs,
		MessageInfos:      file_proto_shim_v1_shim_proto_msgTypes,
	}.Build()
	File_proto_shim_v1_shim_proto = out.File
	file_proto_shim_v1_shim_proto_goTypes = nil
	file_proto_shim_v1_shim_proto_depIdxs = nil
}
